<?php
/**
 * Help.php
 *
 * This file is part of GCMS > MODULE MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: 
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */

class Help
{

	public function __construct()
	{

	}
}
