<?php

/**
 * SarfejoService.php
 *
 * This file is part of GCMS > MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: gcms_sarfejo_service
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */

class SarfejoService
{

	public function __construct()
	{

	}

	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"INSERT INTO `gcms_sarfejo_service` (
				         `id`  , 
                         `type`  , 
                         `id_group`  , 
                         `id_user`  , 
                         `id_jobinfo`  , 
                         `title`  , 
                         `text`  , 
                         `fee`  , 
                         `status`  , 
                         `admin_rank`  , 
                         `user_rank`  , 
                         `visitor`  , 
                         `created_date`  , 
                         `modify_date` 
						) VALUES(
						 NULL  , 
                         %n  , 
                         %i  , 
                         %i  , 
                         %i  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n 
						)", array($arr['type'] , $arr['id_group'] , $arr['id_user'] , $arr['id_jobinfo'] , $arr['title'] , $arr['text'] , $arr['fee'] , $arr['status'] , $arr['admin_rank'] , $arr['user_rank'] , $arr['visitor'] , $arr['created_date'] , $arr['modify_date']));
		return $GLOBALS['GCMS_DB']->query($query);
	}
    
    public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"UPDATE `gcms_sarfejo_service` SET
						 `id` =  %i 
                         [ , `type` = %N ] 
                         [ , `id_group` = %I ] 
                         [ , `id_user` = %I ] 
                         [ , `id_jobinfo` = %I ] 
                         [ , `title` = %N ] 
                         [ , `text` = %N ] 
                         [ , `fee` = %N ] 
                         [ , `status` = %N ] 
                         [ , `admin_rank` = %N ] 
                         [ , `user_rank` = %N ] 
                         [ , `visitor` = %N ] 
                         [ , `created_date` = %N ] 
                         [ , `modify_date` = %N ] 
                        
						WHERE `id` =  %i",
						array($arr['id'] , $arr['type'] , $arr['id_group'] , $arr['id_user'] , $arr['id_jobinfo'] , $arr['title'] , $arr['text'] , $arr['fee'] , $arr['status'] , $arr['admin_rank'] , $arr['user_rank'] , $arr['visitor'] , $arr['created_date'] , $arr['modify_date'], $arr['id']));
		return $GLOBALS['GCMS_DB']->query($query);
	}

    public function get($arr, $list = false, $order = "" , $limit = "", $join_param = "" , $group = "")
	{
		$join_query_helper=array();
		if($join_param=="user_group")
		{
			$join_query_helper['select']=", `gcms_sarfejo_user`.`email` as `user_email`, `gcms_sarfejo_user`.`name` as `user_name`, `gcms_sarfejo_jobgroup`.`name` as `group_name`";
			$join_query_helper['join']="INNER JOIN `gcms_sarfejo_user` ON `gcms_sarfejo_service`.`id_user` = `gcms_sarfejo_user`.`id` INNER JOIN `gcms_sarfejo_jobgroup` ON `gcms_sarfejo_service`.`id_group` = `gcms_sarfejo_jobgroup`.`id`";
		}	
		if($join_param=="sarfejo_group")
		{
			$join_query_helper['select']=" , `gcms_sarfejo_jobgroup`.`name` as `group_name` , `gcms_sarfejo_jobinfo`.`state` as `state` , `gcms_sarfejo_jobinfo`.`city` as `city`  ";
			$join_query_helper['join']=" INNER JOIN `gcms_sarfejo_jobgroup` ON `gcms_sarfejo_jobgroup`.`id` = `gcms_sarfejo_service`.`id_group`   INNER JOIN `gcms_sarfejo_jobinfo` ON `gcms_sarfejo_jobinfo`.`id` = `gcms_sarfejo_service`.`id_jobinfo`   ";
		}
		if($join_param=="jobinfo")
		{
			$join_query_helper['select']=" , `gcms_sarfejo_jobinfo`.`state` as `state` , `gcms_sarfejo_jobinfo`.`city` as `city` ";
			$join_query_helper['join']="  INNER JOIN `gcms_sarfejo_jobinfo` ON `gcms_sarfejo_jobinfo`.`id` = `gcms_sarfejo_service`.`id_jobinfo`  ";
		}
        if ($group != "")
        {
            if ($group == "id_group")
                $groupCount = "  , COUNT(`gcms_sarfejo_service`.`$group`) AS `count` ";
            else
                $groupCount = "  , COUNT(`gcms_sarfejo_jobinfo`.`$group`) AS `count` ";
        }


		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT `gcms_sarfejo_service`.* [ %S ]  [ %S ] FROM `gcms_sarfejo_service` [ %S ] WHERE TRUE
						 [ AND `gcms_sarfejo_service`.`id` = %I ] 
                         [ AND `gcms_sarfejo_service`.`type` = %N ]
                         [ AND `gcms_sarfejo_service`.`id_group` = %I ] 
                         [ AND `gcms_sarfejo_service`.`id_user` = %I ] 
                         [ AND `gcms_sarfejo_service`.`id_jobinfo` = %I ] 
                         [ AND `gcms_sarfejo_service`.`title` = %N ]
                         [ AND `gcms_sarfejo_service`.`text` = %N ]
                         [ AND `gcms_sarfejo_service`.`fee` = %N ]
                         [ AND `gcms_sarfejo_service`.`fee` >= %N ]
                         [ AND `gcms_sarfejo_service`.`fee` <= %N ]
                         [ AND `gcms_sarfejo_service`.`status` = %N ]
                         [ AND `gcms_sarfejo_service`.`admin_rank` = %N ]
                         [ AND `gcms_sarfejo_service`.`user_rank` = %N ]
                         [ AND `gcms_sarfejo_service`.`visitor` = %N ]
                         [ AND `gcms_sarfejo_service`.`created_date` = %N ]
                         [ AND `gcms_sarfejo_service`.`modify_date` = %N ]
                         [ AND `gcms_sarfejo_jobinfo`.`state` = %N ]
                         [ AND `gcms_sarfejo_jobinfo`.`city` = %N ]
                        [ AND (`gcms_sarfejo_service`.`title` LIKE %N OR `gcms_sarfejo_service`.`text` LIKE %N )]
						[ GROUP BY `%S` ]
						[ ORDER BY `gcms_sarfejo_service`.`%S` ] [ %S ]
                        [ LIMIT %I ][ , %I ]
						",
						array($join_query_helper['select'], $groupCount,$join_query_helper['join'],
                            $arr['id'] ,
                            $arr['type'] ,
                            $arr['id_group'] ,
                            $arr['id_user'] ,
                            $arr['id_jobinfo'] ,
                            $arr['title'] ,
                            $arr['text'] ,
                            $arr['fee'] ,
                            $arr['feefrom'] ,
                            $arr['feeto'] ,
                            $arr['status'] ,
                            $arr['admin_rank'] ,
                            $arr['user_rank'] ,
                            $arr['visitor'] ,
                            $arr['created_date'] ,
                            $arr['modify_date'],
                            $arr['state'],
                            $arr['city'],
                            $arr['search'],
                            $arr['search'],
                            $group ,
                            $order['by'],
                            $order['sort'] ,
                            $limit['start'],$limit['end']));
        //echo $query;
        if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}
    
    public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT COUNT(*) as Num FROM `gcms_sarfejo_service` WHERE TRUE
					    [ AND `id` = %I ] 
                         [ AND `type` = %N ]
                         [ AND `id_group` = %I ] 
                         [ AND `id_user` = %I ] 
                         [ AND `id_jobinfo` = %I ] 
                         [ AND `title` = %N ]
                         [ AND `text` = %N ]
                         [ AND `fee` = %N ]
                         [ AND `status` = %N ]
                         [ AND `admin_rank` = %N ]
                         [ AND `user_rank` = %N ]
                         [ AND `visitor` = %N ]
                         [ AND `created_date` = %N ]
                         [ AND `modify_date` = %N ]
                        
						",
						array($arr['id'] , $arr['type'] , $arr['id_group'] , $arr['id_user'] , $arr['id_jobinfo'] , $arr['title'] , $arr['text'] , $arr['fee'] , $arr['status'] , $arr['admin_rank'] , $arr['user_rank'] , $arr['visitor'] , $arr['created_date'] , $arr['modify_date']));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}

	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query("DELETE FROM `gcms_sarfejo_service`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}

}   
    