<?php

/**
 * SarfejoComment.php
 *
 * This file is part of GCMS > MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: gcms_sarfejo_comment
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */

class SarfejoComment
{

	public function __construct()
	{

	}

	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"INSERT INTO `gcms_sarfejo_comment` (
				         `id`  , 
                         `id_user`  , 
                         `id_service`  , 
                         `text`  , 
                         `status`  , 
                         `plus`  , 
                         `minus`  , 
                         `score`  , 
                         `created_date` 
						) VALUES(
						 NULL  , 
                         %i  , 
                         %i  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n 
						)", array($arr['id_user'] , $arr['id_service'] , $arr['text'] , $arr['status'] , $arr['plus'] , $arr['minus'] , $arr['score'] , $arr['created_date']));
		return $GLOBALS['GCMS_DB']->query($query);
	}
    
    public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"UPDATE `gcms_sarfejo_comment` SET
						 `id` =  %i 
                         [ , `id_user` = %I ] 
                         [ , `id_service` = %I ] 
                         [ , `text` = %N ] 
                         [ , `status` = %N ] 
                         [ , `plus` = %N ] 
                         [ , `minus` = %N ] 
                         [ , `score` = %N ] 
                         [ , `created_date` = %N ] 
                        
						WHERE `id` =  %i",
						array($arr['id'] , $arr['id_user'] , $arr['id_service'] , $arr['text'] , $arr['status'] , $arr['plus'] , $arr['minus'] , $arr['score'] , $arr['created_date'], $arr['id']));
		return $GLOBALS['GCMS_DB']->query($query);
	}

    public function get($arr, $list = false, $order = "" , $limit = "")
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT * FROM `gcms_sarfejo_comment` WHERE TRUE
						 [ AND `id` = %I ] 
                         [ AND `id_user` = %I ] 
                         [ AND `id_service` = %I ] 
                         [ AND `text` = %N ]
                         [ AND `status` = %N ]
                         [ AND `plus` = %N ]
                         [ AND `minus` = %N ]
                         [ AND `score` = %N ]
                         [ AND `created_date` = %N ]
                        
						[ ORDER BY `%S` ] [ %S ] 
                        [ LIMIT %I ][ , %I ]
						",
						array($arr['id'] , $arr['id_user'] , $arr['id_service'] , $arr['text'] , $arr['status'] , $arr['plus'] , $arr['minus'] , $arr['score'] , $arr['created_date'], $order['by'], $order['sort'] ,$limit['start'],$limit['end']));
		if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}
    
    public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT COUNT(*) as Num FROM `gcms_sarfejo_comment` WHERE TRUE
					    [ AND `id` = %I ] 
                         [ AND `id_user` = %I ] 
                         [ AND `id_service` = %I ] 
                         [ AND `text` = %N ]
                         [ AND `status` = %N ]
                         [ AND `plus` = %N ]
                         [ AND `minus` = %N ]
                         [ AND `score` = %N ]
                         [ AND `created_date` = %N ]
                        
						",
						array($arr['id'] , $arr['id_user'] , $arr['id_service'] , $arr['text'] , $arr['status'] , $arr['plus'] , $arr['minus'] , $arr['score'] , $arr['created_date']));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}

	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query("DELETE FROM `gcms_sarfejo_comment`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}

}   
    