<?php

/**
 * SarfejoJobinfo.php
 *
 * This file is part of GCMS > MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: gcms_sarfejo_jobinfo
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */

class SarfejoJobinfo
{

	public function __construct()
	{

	}

	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"INSERT INTO `gcms_sarfejo_jobinfo` (
				         `id`  , 
                         `id_user`  , 
                         `co_name`  , 
                         `name`  , 
                         `state`  , 
                         `city`  , 
                         `address`  , 
                         `latitude`  , 
                         `longitude`  , 
                         `tell`  , 
                         `cell`  , 
                         `email`  , 
                         `url`  , 
                         `created_date`  , 
                         `modify_date`  , 
                         `status` 
						) VALUES(
						 NULL  , 
                         %i  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n 
						)", array($arr['id_user'] , $arr['co_name'] , $arr['name'] , $arr['state'] , $arr['city'] , $arr['address'] , $arr['latitude'] , $arr['longitude'] , $arr['tell'] , $arr['cell'] , $arr['email'] , $arr['url'] , $arr['created_date'] , $arr['modify_date'] , $arr['status']));
		return $GLOBALS['GCMS_DB']->query($query);
	}
    
    public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"UPDATE `gcms_sarfejo_jobinfo` SET
						 `id` =  %i 
                         [ , `id_user` = %I ] 
                         [ , `co_name` = %N ] 
                         [ , `name` = %N ] 
                         [ , `state` = %N ] 
                         [ , `city` = %N ] 
                         [ , `address` = %N ] 
                         [ , `latitude` = %N ] 
                         [ , `longitude` = %N ] 
                         [ , `tell` = %N ] 
                         [ , `cell` = %N ] 
                         [ , `email` = %N ] 
                         [ , `url` = %N ] 
                         [ , `created_date` = %N ] 
                         [ , `modify_date` = %N ] 
                         [ , `status` = %N ] 
                        
						WHERE `id` =  %i",
						array($arr['id'] , $arr['id_user'] , $arr['co_name'] , $arr['name'] , $arr['state'] , $arr['city'] , $arr['address'] , $arr['latitude'] , $arr['longitude'] , $arr['tell'] , $arr['cell'] , $arr['email'] , $arr['url'] , $arr['created_date'] , $arr['modify_date'] , $arr['status'], $arr['id']));
		return $GLOBALS['GCMS_DB']->query($query);
	}

    public function get($arr, $list = false, $order = "" , $limit = "", $join_param = "")
	{
		$join_query_helper=array();
		if($join_param=="sarfejo_user")
		{
			$join_query_helper['select']=", `gcms_sarfejo_user`.`email` as `user_email`, `gcms_sarfejo_user`.`name` as `user_name`";
			$join_query_helper['join']="INNER JOIN `gcms_sarfejo_user` ON `gcms_sarfejo_jobinfo`.`id_user` = `gcms_sarfejo_user`.`id`";
		}		
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT `gcms_sarfejo_jobinfo`.* [ %S ] FROM `gcms_sarfejo_jobinfo` [ %S ] WHERE TRUE
						 [ AND `gcms_sarfejo_jobinfo`.`id` = %I ] 
                         [ AND `gcms_sarfejo_jobinfo`.`id_user` = %I ] 
                         [ AND `gcms_sarfejo_jobinfo`.`co_name` = %N ]
                         [ AND `gcms_sarfejo_jobinfo`.`name` = %N ]
                         [ AND `gcms_sarfejo_jobinfo`.`state` = %N ]
                         [ AND `gcms_sarfejo_jobinfo`.`city` = %N ]
                         [ AND `gcms_sarfejo_jobinfo`.`address` = %N ]
                         [ AND `gcms_sarfejo_jobinfo`.`latitude` = %N ]
                         [ AND `gcms_sarfejo_jobinfo`.`longitude` = %N ]
                         [ AND `gcms_sarfejo_jobinfo`.`tell` = %N ]
                         [ AND `gcms_sarfejo_jobinfo`.`cell` = %N ]
                         [ AND `gcms_sarfejo_jobinfo`.`email` = %N ]
                         [ AND `gcms_sarfejo_jobinfo`.`url` = %N ]
                         [ AND `gcms_sarfejo_jobinfo`.`created_date` = %N ]
                         [ AND `gcms_sarfejo_jobinfo`.`modify_date` = %N ]
                         [ AND `gcms_sarfejo_jobinfo`.`status` = %N ]
						 [ AND (`gcms_sarfejo_jobinfo`.`name` LIKE %N OR `gcms_sarfejo_jobinfo`.`co_name` LIKE %N )]
                        
						[ ORDER BY `gcms_sarfejo_jobinfo`.`%S` ] [ %S ] 
                        [ LIMIT %I ][ , %I ]
						",
						array($join_query_helper['select'], $join_query_helper['join'], $arr['id'] , $arr['id_user'] , $arr['co_name'] , $arr['name'] , $arr['state'] , $arr['city'] , $arr['address'] , $arr['latitude'] , $arr['longitude'] , $arr['tell'] , $arr['cell'] , $arr['email'] , $arr['url'] , $arr['created_date'] , $arr['modify_date'] , $arr['status'], $arr['search'], $arr['search'], $order['by'], $order['sort'] ,$limit['start'],$limit['end']));
		if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}
    
    public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT COUNT(*) as Num FROM `gcms_sarfejo_jobinfo` WHERE TRUE
					    [ AND `id` = %I ] 
                         [ AND `id_user` = %I ] 
                         [ AND `co_name` = %N ]
                         [ AND `name` = %N ]
                         [ AND `state` = %N ]
                         [ AND `city` = %N ]
                         [ AND `address` = %N ]
                         [ AND `latitude` = %N ]
                         [ AND `longitude` = %N ]
                         [ AND `tell` = %N ]
                         [ AND `cell` = %N ]
                         [ AND `email` = %N ]
                         [ AND `url` = %N ]
                         [ AND `created_date` = %N ]
                         [ AND `modify_date` = %N ]
                         [ AND `status` = %N ]
						 [ AND (`name` LIKE %N OR `co_name` LIKE %N )]
                        
						",
						array($arr['id'] , $arr['id_user'] , $arr['co_name'] , $arr['name'] , $arr['state'] , $arr['city'] , $arr['address'] , $arr['latitude'] , $arr['longitude'] , $arr['tell'] , $arr['cell'] , $arr['email'] , $arr['url'] , $arr['created_date'] , $arr['modify_date'] , $arr['status'], $arr['search'], $arr['search']));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}

	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query("DELETE FROM `gcms_sarfejo_jobinfo`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}

}   
    