
<?php

/**
 * MetaPage.php
 *
 * This file is part of GCMS > MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: gcms_meta_page
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */

class MetaPage
{

	public function __construct()
	{

	}

	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"INSERT INTO `gcms_meta_page` (
				         `id`  , 
                         `page_id`  , 
                         `meta_key`  , 
                         `meta_value` 
						) VALUES(
						 NULL  , 
                         %i  , 
                         %n  , 
                         %n 
						)", array($arr['page_id'] , $arr['meta_key'] , $arr['meta_value']));
		return $GLOBALS['GCMS_DB']->query($query);
	}
    
    public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"UPDATE `gcms_meta_page` SET
						 `id` =  %i 
                         [ , `page_id` = %I ] 
                         [ , `meta_key` = %N ] 
                         [ , `meta_value` = %N ] 
                        
						WHERE `id` =  %i",
						array($arr['id'] , $arr['page_id'] , $arr['meta_key'] , $arr['meta_value'] , $arr['id']));
		return $GLOBALS['GCMS_DB']->query($query);
	}

    public function get($arr, $list = false, $order = "" , $limit = "")
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT * FROM `gcms_meta_page` WHERE TRUE
						 [ AND `id` = %I ] 
                         [ AND `page_id` = %I ] 
                         [ AND `meta_key` = %N ]
                         [ AND `meta_value` = %N ]
                        
						[ ORDER BY `%S` ] [ %S ] 
                        [ LIMIT %I ][ , %I ]
						",
						array($arr['id'] , $arr['page_id'] , $arr['meta_key'] , $arr['meta_value'], $order['by'], $order['sort'] ,$limit['start'],$limit['end']));
		if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}
    
    public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT COUNT(*) as Num FROM `gcms_meta_page` WHERE TRUE
					    [ AND `id` = %I ] 
                         [ AND `page_id` = %I ] 
                         [ AND `meta_key` = %N ]
                         [ AND `meta_value` = %N ]
                        
						",
						array($arr['id'] , $arr['page_id'] , $arr['meta_key'] , $arr['meta_value']));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}

	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query("DELETE FROM `gcms_meta_page`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}

}   
    