<?php

/**
 * SalamatGroup.php
 *
 * This file is part of GCMS > MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: gcms_salamat_group
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */

class SalamatGroup
{

	public function __construct()
	{

	}

	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"INSERT INTO `gcms_salamat_group` (
				         `id`  , 
                         `id_parent`  , 
                         `tag`  , 
                         `title`  , 
                         `status` 
						) VALUES(
						 NULL  , 
                         %i  , 
                         %n  , 
                         %n  , 
                         %n 
						)",
						array($arr['id_parent'], $arr['tag'], $arr['title'], $arr['status']));
		return $GLOBALS['GCMS_DB']->query($query);
	}

	public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"UPDATE `gcms_salamat_group` SET
						 `id` =  %i 
                         [ , `id_parent` = %I ] 
                         [ , `tag` = %N ] 
                         [ , `title` = %N ] 
                         [ , `status` = %N ] 
                        
						WHERE `id` =  %i",
						array(
									$arr['id'],
									$arr['id_parent'],
									$arr['tag'],
									$arr['title'],
									$arr['status'],
									$arr['id']
						));
		return $GLOBALS['GCMS_DB']->query($query);
	}

	public function get($arr, $list = false, $order = "", $limit = "")
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT * FROM `gcms_salamat_group` WHERE TRUE
						 [ AND `id` = %I ] 
                         [ AND `id_parent` = %I ] 
                         [ AND `tag` = %N ]
                         [ AND `title` = %N ]
                         [ AND `status` = %N ]
                        
						[ ORDER BY `%S` ] [ %S ] 
                        [ LIMIT %I ][ , %I ]
						",
						array(
									$arr['id'],
									$arr['id_parent'],
									$arr['tag'],
									$arr['title'],
									$arr['status'],
									$order['by'],
									$order['sort'],
									$limit['start'],
									$limit['end']
						));
		if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}

	public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT COUNT(*) as Num FROM `gcms_salamat_group` WHERE TRUE
					    [ AND `id` = %I ] 
                         [ AND `id_parent` = %I ] 
                         [ AND `tag` = %N ]
                         [ AND `title` = %N ]
                         [ AND `status` = %N ]
                        
						",
						array(
									$arr['id'],
									$arr['id_parent'],
									$arr['tag'],
									$arr['title'],
									$arr['status']
						));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}

	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query("DELETE FROM `gcms_salamat_group`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}

}
   
    
