<?php

/**
 * SalamatInfo.php
 *
 * This file is part of GCMS > MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: gcms_salamat_info
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */

class SalamatInfo
{

	public function __construct()
	{

	}

	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"INSERT INTO `gcms_salamat_info` (
				         `id`  , 
                         `id_area`  , 
                         `status`  , 
                         `addresalamat`  , 
                         `tell`  , 
                         `fax`  , 
                         `cell`  , 
                         `email`  , 
                         `url`  , 
                         `zip`  , 
                         `latitude`  , 
                         `longitude`  , 
                         `salamat_score`  , 
                         `user_score`  , 
                         `title`  , 
                         `text`  , 
                         `type` 
						) VALUES(
						 NULL  , 
                         %i  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n 
						)",
						array(
									$arr['id_area'],
									$arr['status'],
									$arr['addresalamat'],
									$arr['tell'],
									$arr['fax'],
									$arr['cell'],
									$arr['email'],
									$arr['url'],
									$arr['zip'],
									$arr['latitude'],
									$arr['longitude'],
									$arr['salamat_score'],
									$arr['user_score'],
									$arr['title'],
									$arr['text'],
									$arr['type']
						));
		return $GLOBALS['GCMS_DB']->query($query);
	}

	public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"UPDATE `gcms_salamat_info` SET
						 `id` =  %i 
                         [ , `id_area` = %I ] 
                         [ , `status` = %N ] 
                         [ , `addresalamat` = %N ] 
                         [ , `tell` = %N ] 
                         [ , `fax` = %N ] 
                         [ , `cell` = %N ] 
                         [ , `email` = %N ] 
                         [ , `url` = %N ] 
                         [ , `zip` = %N ] 
                         [ , `latitude` = %N ] 
                         [ , `longitude` = %N ] 
                         [ , `salamat_score` = %N ] 
                         [ , `user_score` = %N ] 
                         [ , `title` = %N ] 
                         [ , `text` = %N ] 
                         [ , `type` = %N ] 
                        
						WHERE `id` =  %i",
						array(
									$arr['id'],
									$arr['id_area'],
									$arr['status'],
									$arr['addresalamat'],
									$arr['tell'],
									$arr['fax'],
									$arr['cell'],
									$arr['email'],
									$arr['url'],
									$arr['zip'],
									$arr['latitude'],
									$arr['longitude'],
									$arr['salamat_score'],
									$arr['user_score'],
									$arr['title'],
									$arr['text'],
									$arr['type'],
									$arr['id']
						));
		return $GLOBALS['GCMS_DB']->query($query);
	}

	public function get($arr, $list = false, $order = "", $limit = "", $join_param = "")
	{
		$join_query_helper=array();
		if($join_param=="area"||$join_param=="both")
		{
			$join_query_helper['select1']=", `gcms_salamat_area`.`name` as area_name ";
			$join_query_helper['join1']="INNER JOIN `gcms_salamat_area` ON `gcms_salamat_info`.`id_area` = `gcms_salamat_area`.`id`";
			if(isset($arr['id_area0']))
			{
				$join_query_helper['where1']="AND `gcms_salamat_area`.`id_parent` = ";
				$join_query_helper['param1']=$arr['id_area0'];
			}
		} 
		if($join_param=="group"||$join_param=="both")
		{
			$join_query_helper['select2']=", `gcms_salamat_group`.`tag` as group_tag ";
			$join_query_helper['join2']="INNER JOIN `gcms_salamat_rel_groupinfo` ON `gcms_salamat_info`.`id` = `gcms_salamat_rel_groupinfo`.`id_info` INNER JOIN `gcms_salamat_group` ON `gcms_salamat_group`.`id` = `gcms_salamat_rel_groupinfo`.`id_group`";
			$join_query_helper['groupby2']=" GROUP BY `gcms_salamat_rel_groupinfo`.`id_info` ";
			if(isset($arr['group']))
			{
				$join_query_helper['where2']="AND `gcms_salamat_group`.`tag` LIKE ";
				$join_query_helper['param2']=$arr['group'];
			}
		}
		
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT `gcms_salamat_info`.* [ %S ] [ %S ] FROM `gcms_salamat_info` [ %S ] [ %S ]
						WHERE TRUE
						[ %S ][ %N ][ %S ][ %N ]
						 [ AND `gcms_salamat_info`.`id` = %I ] 
                         [ AND `gcms_salamat_info`.`id_area` = %I ] 
                         [ AND `gcms_salamat_info`.`status` = %N ] 
                         [ AND `gcms_salamat_info`.`status` != %N ]
                         [ AND `gcms_salamat_info`.`addresalamat` = %N ]
                         [ AND `gcms_salamat_info`.`tell` = %N ]
                         [ AND `gcms_salamat_info`.`fax` = %N ]
                         [ AND `gcms_salamat_info`.`cell` = %N ]
                         [ AND `gcms_salamat_info`.`email` = %N ]
                         [ AND `gcms_salamat_info`.`url` = %N ]
                         [ AND `gcms_salamat_info`.`zip` = %N ]
                         [ AND `gcms_salamat_info`.`latitude` = %N ]
                         [ AND `gcms_salamat_info`.`longitude` = %N ]
                         [ AND `gcms_salamat_info`.`salamat_score` = %N ]
                         [ AND `gcms_salamat_info`.`user_score` = %N ]
                         [ AND `gcms_salamat_info`.`title` = %N ]
                         [ AND `gcms_salamat_info`.`text` = %N ]
                         [ AND `gcms_salamat_info`.`type` = %N ]
						[ AND (`gcms_salamat_info`.`text` LIKE %N OR `gcms_salamat_info`.`title` LIKE %N )]
						[ AND `gcms_salamat_info`.`addresalamat` LIKE %N ]
						[ %S ]
						[ ORDER BY `gcms_salamat_info`.`%S` ] [ %S ] 
                        [ LIMIT %I ][ , %I ]
						",
						array(
									$join_query_helper['select1'],
									$join_query_helper['select2'],
									$join_query_helper['join1'],
									$join_query_helper['join2'],
									$join_query_helper['where1'],
									$join_query_helper['param1'],
									$join_query_helper['where2'],
									$join_query_helper['param2'],
									$arr['id'],
									$arr['id_area'],
									$arr['status'],
									$arr['status_not'],
									$arr['addresalamat'],
									$arr['tell'],
									$arr['fax'],
									$arr['cell'],
									$arr['email'],
									$arr['url'],
									$arr['zip'],
									$arr['latitude'],
									$arr['longitude'],
									$arr['salamat_score'],
									$arr['user_score'],
									$arr['title'],
									$arr['text'],
									$arr['type'],
									$arr['search'],
									$arr['search'],
									$arr['search_address'],
									$join_query_helper['groupby2'],
									$order['by'],
									$order['sort'],
									$limit['start'],
									$limit['end']
						));
		if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}

	public function get_count($arr)
	{
		$join_query_helper=array();
		if(isset($arr['id_area0']))
		{
			$join_query_helper['join1']="INNER JOIN `gcms_salamat_area` ON `gcms_salamat_info`.`id_area` = `gcms_salamat_area`.`id`";
			$join_query_helper['where1']="AND `gcms_salamat_area`.`id_parent` = ";
			$join_query_helper['param1']=$arr['id_area0'];
		}
		if(isset($arr['group']))
		{
			$join_query_helper['join2']="INNER JOIN `gcms_salamat_rel_groupinfo` ON `gcms_salamat_info`.`id` = `gcms_salamat_rel_groupinfo`.`id_info` INNER JOIN `gcms_salamat_group` ON `gcms_salamat_group`.`id` = `gcms_salamat_rel_groupinfo`.`id_group`";
			$join_query_helper['where2']="AND `gcms_salamat_group`.`tag` LIKE ";
			$join_query_helper['param2']=$arr['group'];
		}
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT COUNT(*) as Num FROM `gcms_salamat_info`  [ %S ] [ %S ]
						WHERE TRUE
						[ %S ][ %N ][ %S ][ %N ]
						 [ AND `gcms_salamat_info`.`id` = %I ] 
                         [ AND `gcms_salamat_info`.`id_area` = %I ] 
                         [ AND `gcms_salamat_info`.`status` = %N ] 
                         [ AND `gcms_salamat_info`.`status` != %N ]
                         [ AND `gcms_salamat_info`.`addresalamat` = %N ]
                         [ AND `gcms_salamat_info`.`tell` = %N ]
                         [ AND `gcms_salamat_info`.`fax` = %N ]
                         [ AND `gcms_salamat_info`.`cell` = %N ]
                         [ AND `gcms_salamat_info`.`email` = %N ]
                         [ AND `gcms_salamat_info`.`url` = %N ]
                         [ AND `gcms_salamat_info`.`zip` = %N ]
                         [ AND `gcms_salamat_info`.`latitude` = %N ]
                         [ AND `gcms_salamat_info`.`longitude` = %N ]
                         [ AND `gcms_salamat_info`.`salamat_score` = %N ]
                         [ AND `gcms_salamat_info`.`user_score` = %N ]
                         [ AND `gcms_salamat_info`.`title` = %N ]
                         [ AND `gcms_salamat_info`.`text` = %N ]
                         [ AND `gcms_salamat_info`.`type` = %N ]
						[ AND (`gcms_salamat_info`.`text` LIKE %N OR `gcms_salamat_info`.`title` LIKE %N )]
						[ AND `gcms_salamat_info`.`addresalamat` LIKE %N ]
                        
						",
						array(
									$join_query_helper['join1'],
									$join_query_helper['join2'],
									$join_query_helper['where1'],
									$join_query_helper['param1'],
									$join_query_helper['where2'],
									$join_query_helper['param2'],
									$arr['id'],
									$arr['id_area'],
									$arr['status'],
									$arr['status_not'],
									$arr['addresalamat'],
									$arr['tell'],
									$arr['fax'],
									$arr['cell'],
									$arr['email'],
									$arr['url'],
									$arr['zip'],
									$arr['latitude'],
									$arr['longitude'],
									$arr['salamat_score'],
									$arr['user_score'],
									$arr['title'],
									$arr['text'],
									$arr['type'],
									$arr['search'],
									$arr['search'],
									$arr['search_address']
						));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}

	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query("DELETE FROM `gcms_salamat_info`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}

}
   
    
