<?php

/**
 * SalamatUser.php
 *
 * This file is part of GCMS > MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: gcms_salamat_user
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */

class SalamatUser
{

	public function __construct()
	{

	}

	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"INSERT INTO `gcms_salamat_user` (
				         `id`  , 
                         `username`  , 
                         `email`  , 
                         `email_temp_code`  , 
                         `password`  , 
                         `password_salt`  , 
                         `password_temp_code`  , 
                         `status`  , 
                         `user_level`  , 
                         `date_created`  , 
                         `name`  , 
                         `cell`  , 
                         `cell_temp_code`  , 
                         `birth_date`  , 
                         `gender`  , 
                         `city`  , 
                         `address`  , 
                         `avatar`  , 
                         `created_by`  , 
                         `credit` 
						) VALUES(
						 NULL  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %i  , 
                         %n 
						)",
						array(
									$arr['username'],
									$arr['email'],
									$arr['email_temp_code'],
									$arr['password'],
									$arr['password_salt'],
									$arr['password_temp_code'],
									$arr['status'],
									$arr['user_level'],
									$arr['date_created'],
									$arr['name'],
									$arr['cell'],
									$arr['cell_temp_code'],
									$arr['birth_date'],
									$arr['gender'],
									$arr['city'],
									$arr['address'],
									$arr['avatar'],
									$arr['created_by'],
									$arr['credit']
						));
		return $GLOBALS['GCMS_DB']->query($query);
	}

	public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"UPDATE `gcms_salamat_user` SET
						 `id` =  %i 
                         [ , `username` = %N ] 
                         [ , `email` = %N ] 
                         [ , `email_temp_code` = %N ] 
                         [ , `password` = %N ] 
                         [ , `password_salt` = %N ] 
                         [ , `password_temp_code` = %N ] 
                         [ , `status` = %N ] 
                         [ , `user_level` = %N ] 
                         [ , `date_created` = %N ] 
                         [ , `name` = %N ] 
                         [ , `cell` = %N ] 
                         [ , `cell_temp_code` = %N ] 
                         [ , `birth_date` = %N ] 
                         [ , `gender` = %N ] 
                         [ , `city` = %N ] 
                         [ , `address` = %N ] 
                         [ , `avatar` = %N ] 
                         [ , `created_by` = %I ] 
                         [ , `credit` = %N ] 
                        
						WHERE `id` =  %i",
						array(
									$arr['id'],
									$arr['username'],
									$arr['email'],
									$arr['email_temp_code'],
									$arr['password'],
									$arr['password_salt'],
									$arr['password_temp_code'],
									$arr['status'],
									$arr['user_level'],
									$arr['date_created'],
									$arr['name'],
									$arr['cell'],
									$arr['cell_temp_code'],
									$arr['birth_date'],
									$arr['gender'],
									$arr['city'],
									$arr['address'],
									$arr['avatar'],
									$arr['created_by'],
									$arr['credit'],
									$arr['id']
						));
		return $GLOBALS['GCMS_DB']->query($query);
	}

	public function get($arr, $list = false, $order = "", $limit = "")
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT * FROM `gcms_salamat_user` WHERE TRUE
						 [ AND `id` = %I ] 
                         [ AND `username` = %N ]
                         [ AND `email` = %N ]
                         [ AND `email_temp_code` = %N ]
                         [ AND `password` = %N ]
                         [ AND `password_salt` = %N ]
                         [ AND `password_temp_code` = %N ]
                         [ AND `status` = %N ]
                         [ AND `status` != %N ]
                         [ AND `user_level` = %N ]
                         [ AND `date_created` = %N ]
                         [ AND `name` = %N ]
                         [ AND `cell` = %N ]
                         [ AND `cell_temp_code` = %N ]
                         [ AND `birth_date` = %N ]
                         [ AND `gender` = %N ]
                         [ AND `city` = %N ]
                         [ AND `address` = %N ]
                         [ AND `avatar` = %N ]
                         [ AND `created_by` = %I ] 
                         [ AND `credit` = %N ]
						 [ AND (`username` LIKE %N OR `name` LIKE %N OR `email` LIKE %N OR `cell` LIKE %N )]
                        
						[ ORDER BY `%S` ] [ %S ] 
                        [ LIMIT %I ][ , %I ]
						",
						array(
									$arr['id'],
									$arr['username'],
									$arr['email'],
									$arr['email_temp_code'],
									$arr['password'],
									$arr['password_salt'],
									$arr['password_temp_code'],
									$arr['status'],
									$arr['status_not'],
									$arr['user_level'],
									$arr['date_created'],
									$arr['name'],
									$arr['cell'],
									$arr['cell_temp_code'],
									$arr['birth_date'],
									$arr['gender'],
									$arr['city'],
									$arr['address'],
									$arr['avatar'],
									$arr['created_by'],
									$arr['credit'],
									$arr['search'],
									$arr['search'],
									$arr['search'],
									$arr['search'],
									$order['by'],
									$order['sort'],
									$limit['start'],
									$limit['end']
						));
		if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}

	public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT COUNT(*) as Num FROM `gcms_salamat_user` WHERE TRUE
					    [ AND `id` = %I ] 
                         [ AND `username` = %N ]
                         [ AND `email` = %N ]
                         [ AND `email_temp_code` = %N ]
                         [ AND `password` = %N ]
                         [ AND `password_salt` = %N ]
                         [ AND `password_temp_code` = %N ]
                         [ AND `status` = %N ]
                         [ AND `user_level` = %N ]
                         [ AND `date_created` = %N ]
                         [ AND `name` = %N ]
                         [ AND `cell` = %N ]
                         [ AND `cell_temp_code` = %N ]
                         [ AND `birth_date` = %N ]
                         [ AND `gender` = %N ]
                         [ AND `city` = %N ]
                         [ AND `address` = %N ]
                         [ AND `avatar` = %N ]
                         [ AND `created_by` = %I ] 
                         [ AND `credit` = %N ]
						 [ AND (`username` LIKE %N OR `name` LIKE %N OR `email` LIKE %N OR `cell` LIKE %N )]
                        
						",
						array(
									$arr['id'],
									$arr['username'],
									$arr['email'],
									$arr['email_temp_code'],
									$arr['password'],
									$arr['password_salt'],
									$arr['password_temp_code'],
									$arr['status'],
									$arr['user_level'],
									$arr['date_created'],
									$arr['name'],
									$arr['cell'],
									$arr['cell_temp_code'],
									$arr['birth_date'],
									$arr['gender'],
									$arr['city'],
									$arr['address'],
									$arr['avatar'],
									$arr['created_by'],
									$arr['credit'],
									$arr['search'],
									$arr['search'],
									$arr['search'],
									$arr['search']
						));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}

	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query("DELETE FROM `gcms_salamat_user`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}

}
