<?php

/**
 * ShirazRelDiscountUser.php
 *
 * This file is part of GCMS > MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: gcms_shiraz_rel_discount_user
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */

class ShirazRelDiscountUser
{

	public function __construct()
	{

	}

	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"INSERT INTO `gcms_shiraz_rel_discount_user` (
				         `id`  , 
                         `id_discount`  , 
                         `id_user`  , 
                         `date_sell`  , 
                         `coupon_no`  , 
                         `coupon_pass` 
						) VALUES(
						 NULL  , 
                         %i  , 
                         %i  , 
                         %n  , 
                         %n  , 
                         %n 
						)", array($arr['id_discount'] , $arr['id_user'] , $arr['date_sell'] , $arr['coupon_no'] , $arr['coupon_pass']));
		return $GLOBALS['GCMS_DB']->query($query);
	}
    
    public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"UPDATE `gcms_shiraz_rel_discount_user` SET
						 `id` =  %i 
                         [ , `id_discount` = %I ] 
                         [ , `id_user` = %I ] 
                         [ , `date_sell` = %N ] 
                         [ , `coupon_no` = %N ] 
                         [ , `coupon_pass` = %N ] 
                        
						WHERE `id` =  %i",
						array($arr['id'] , $arr['id_discount'] , $arr['id_user'] , $arr['date_sell'] , $arr['coupon_no'] , $arr['coupon_pass'], $arr['id']));
		return $GLOBALS['GCMS_DB']->query($query);
	}

    public function get($arr, $list = false, $order = "" , $limit = "", $join_param = "")
	{
		$join_query_helper=array();
		if($join_param=="shiraz_user")
		{
			$join_query_helper['select']=", `gcms_shiraz_user`.`username`, `gcms_shiraz_user`.`email`, `gcms_shiraz_user`.`name`, `gcms_shiraz_user`.`cell`";
			$join_query_helper['join']="INNER JOIN `gcms_shiraz_user` ON `gcms_shiraz_rel_discount_user`.`id_user` = `gcms_shiraz_user`.`id`";
		}
		if($join_param=="shiraz_discount")
		{
			$join_query_helper['select']=", `gcms_shiraz_discount`.`shop_name`, `gcms_shiraz_discount`.`title`, `gcms_shiraz_discount`.`real-price`, `gcms_shiraz_discount`.`discount_percent`, `gcms_shiraz_discount`.`plus_count`";
			$join_query_helper['join']="INNER JOIN `gcms_shiraz_discount` ON `gcms_shiraz_rel_discount_user`.`id_discount` = `gcms_shiraz_discount`.`id`";
		}
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT `gcms_shiraz_rel_discount_user`.* [ %S ] FROM `gcms_shiraz_rel_discount_user` [ %S ] WHERE TRUE
						 [ AND `gcms_shiraz_rel_discount_user`.`id` = %I ] 
                         [ AND `gcms_shiraz_rel_discount_user`.`id_discount` = %I ] 
                         [ AND `gcms_shiraz_rel_discount_user`.`id_user` = %I ] 
                         [ AND `gcms_shiraz_rel_discount_user`.`date_sell` = %N ]
                         [ AND `gcms_shiraz_rel_discount_user`.`coupon_no` = %N ]
                         [ AND `gcms_shiraz_rel_discount_user`.`coupon_pass` = %N ]
                        
						[ ORDER BY `%S` ] [ %S ] 
                        [ LIMIT %I ][ , %I ]
						",
						array(
								$join_query_helper['select'],
								$join_query_helper['join'],
								$arr['id'] , 
								$arr['id_discount'] , 
								$arr['id_user'] , 
								$arr['date_sell'] , 
								$arr['coupon_no'] , 
								$arr['coupon_pass'], 
								$order['by'], 
								$order['sort'] ,
								$limit['start'],
								$limit['end']));
		if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}
    
    public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT COUNT(*) as Num FROM `gcms_shiraz_rel_discount_user` WHERE TRUE
					    [ AND `id` = %I ] 
                         [ AND `id_discount` = %I ] 
                         [ AND `id_user` = %I ] 
                         [ AND `date_sell` = %N ]
                         [ AND `coupon_no` = %N ]
                         [ AND `coupon_pass` = %N ]
                        
						",
						array($arr['id'] , $arr['id_discount'] , $arr['id_user'] , $arr['date_sell'] , $arr['coupon_no'] , $arr['coupon_pass']));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}

	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query("DELETE FROM `gcms_shiraz_rel_discount_user`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}

}   
    