<?php

/**
 * ShirazDiscount.php
 *
 * This file is part of GCMS > MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: gcms_shiraz_discount
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */

class ShirazDiscount
{

	public function __construct()
	{

	}

	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"INSERT INTO `gcms_shiraz_discount` (
				         `id`  , 
                         `id_group`  , 
                         `title`  , 
                         `real-price`  , 
                         `discount_percent`  , 
                         `expire_date`  , 
                         `max_sell`  , 
                         `type_delivery`  , 
                         `plus_count`  , 
                         `shop_name`  , 
                         `shop_address`  , 
                         `shop_tell`  , 
                         `shop_cell`  , 
                         `latitude`  , 
                         `longitude`  , 
                         `url`  , 
                         `shop_specification`  , 
                         `ismoment`  , 
                         `text`  , 
                         `info`  , 
                         `conditions`  , 
                         `status`  , 
                         `id_user_seller`  , 
                         `created_date`  , 
                         `code` 
						) VALUES(
						 NULL  , 
                         %i  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %i  , 
                         %n  , 
                         %n 
						)", array($arr['id_group'] , $arr['title'] , $arr['real-price'] , $arr['discount_percent'] , $arr['expire_date'] , $arr['max_sell'] , $arr['type_delivery'] , $arr['plus_count'] , $arr['shop_name'] , $arr['shop_address'] , $arr['shop_tell'] , $arr['shop_cell'] , $arr['latitude'] , $arr['longitude'] , $arr['url'] , $arr['shop_specification'] , $arr['ismoment'] , $arr['text'] , $arr['info'] , $arr['conditions'] , $arr['status'] , $arr['id_user_seller'] , $arr['created_date'] , $arr['code']));
		return $GLOBALS['GCMS_DB']->query($query);
	}
    
    public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"UPDATE `gcms_shiraz_discount` SET
						 `id` =  %i 
                         [ , `id_group` = %I ] 
                         [ , `title` = %N ] 
                         [ , `real-price` = %N ] 
                         [ , `discount_percent` = %N ] 
                         [ , `expire_date` = %N ] 
                         [ , `max_sell` = %N ] 
                         [ , `type_delivery` = %N ] 
                         [ , `plus_count` = %N ] 
                         [ , `shop_name` = %N ] 
                         [ , `shop_address` = %N ] 
                         [ , `shop_tell` = %N ] 
                         [ , `shop_cell` = %N ] 
                         [ , `latitude` = %N ] 
                         [ , `longitude` = %N ] 
                         [ , `url` = %N ] 
                         [ , `shop_specification` = %N ] 
                         [ , `ismoment` = %N ] 
                         [ , `text` = %N ] 
                         [ , `info` = %N ] 
                         [ , `conditions` = %N ] 
                         [ , `status` = %N ] 
                         [ , `id_user_seller` = %I ] 
                         [ , `created_date` = %N ] 
                         [ , `code` = %N ] 
                        
						WHERE `id` =  %i",
						array($arr['id'] , $arr['id_group'] , $arr['title'] , $arr['real-price'] , $arr['discount_percent'] , $arr['expire_date'] , $arr['max_sell'] , $arr['type_delivery'] , $arr['plus_count'] , $arr['shop_name'] , $arr['shop_address'] , $arr['shop_tell'] , $arr['shop_cell'] , $arr['latitude'] , $arr['longitude'] , $arr['url'] , $arr['shop_specification'] , $arr['ismoment'] , $arr['text'] , $arr['info'] , $arr['conditions'] , $arr['status'] , $arr['id_user_seller'] , $arr['created_date'] , $arr['code'], $arr['id']));
		return $GLOBALS['GCMS_DB']->query($query);
	}

    public function get($arr, $list = false, $order = "" , $limit = "")
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT * FROM `gcms_shiraz_discount` WHERE TRUE
						 [ AND `id` = %I ] 
                         [ AND `id_group` = %I ] 
                         [ AND `title` = %N ]
                         [ AND `real-price` = %N ]
                         [ AND `discount_percent` = %N ]
                         [ AND `expire_date` = %N ]
                         [ AND `max_sell` = %N ]
                         [ AND `type_delivery` = %N ]
                         [ AND `plus_count` = %N ]
                         [ AND `shop_name` = %N ]
                         [ AND `shop_address` = %N ]
                         [ AND `shop_tell` = %N ]
                         [ AND `shop_cell` = %N ]
                         [ AND `latitude` = %N ]
                         [ AND `longitude` = %N ]
                         [ AND `url` = %N ]
                         [ AND `shop_specification` = %N ]
                         [ AND `ismoment` = %N ]
                         [ AND `text` = %N ]
                         [ AND `info` = %N ]
                         [ AND `conditions` = %N ]
                         [ AND `status` = %N ]
                         [ AND `id_user_seller` = %I ] 
                         [ AND `created_date` = %N ]
                         [ AND `code` = %N ]
                         [ AND `expire_date` > %N ]
                         [ AND `expire_date` < %N ]
						[ ORDER BY `%S` ] [ %S ] 
                        [ LIMIT %I ][ , %I ]
						",
						array($arr['id'] , $arr['id_group'] , $arr['title'] , $arr['real-price'] , $arr['discount_percent'] , $arr['expire_date'] , $arr['max_sell'] , $arr['type_delivery'] , $arr['plus_count'] , $arr['shop_name'] , $arr['shop_address'] , $arr['shop_tell'] , $arr['shop_cell'] , $arr['latitude'] , $arr['longitude'] , $arr['url'] , $arr['shop_specification'] , $arr['ismoment'] , $arr['text'] , $arr['info'] , $arr['conditions'] , $arr['status'] , $arr['id_user_seller'] , $arr['created_date'] , $arr['code'],
                            $arr['expire_betweenfrom'],$arr['expire_betweento'],
                            $order['by'], $order['sort'] ,$limit['start'],$limit['end']));
		if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}
    
    public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT COUNT(*) as Num FROM `gcms_shiraz_discount` WHERE TRUE
					    [ AND `id` = %I ] 
                         [ AND `id_group` = %I ] 
                         [ AND `title` = %N ]
                         [ AND `real-price` = %N ]
                         [ AND `discount_percent` = %N ]
                         [ AND `expire_date` = %N ]
                         [ AND `max_sell` = %N ]
                         [ AND `type_delivery` = %N ]
                         [ AND `plus_count` = %N ]
                         [ AND `shop_name` = %N ]
                         [ AND `shop_address` = %N ]
                         [ AND `shop_tell` = %N ]
                         [ AND `shop_cell` = %N ]
                         [ AND `latitude` = %N ]
                         [ AND `longitude` = %N ]
                         [ AND `url` = %N ]
                         [ AND `shop_specification` = %N ]
                         [ AND `ismoment` = %N ]
                         [ AND `text` = %N ]
                         [ AND `info` = %N ]
                         [ AND `conditions` = %N ]
                         [ AND `status` = %N ]
                         [ AND `id_user_seller` = %I ] 
                         [ AND `created_date` = %N ]
                         [ AND `code` = %N ]
                        
						",
						array($arr['id'] , $arr['id_group'] , $arr['title'] , $arr['real-price'] , $arr['discount_percent'] , $arr['expire_date'] , $arr['max_sell'] , $arr['type_delivery'] , $arr['plus_count'] , $arr['shop_name'] , $arr['shop_address'] , $arr['shop_tell'] , $arr['shop_cell'] , $arr['latitude'] , $arr['longitude'] , $arr['url'] , $arr['shop_specification'] , $arr['ismoment'] , $arr['text'] , $arr['info'] , $arr['conditions'] , $arr['status'] , $arr['id_user_seller'] , $arr['created_date'] , $arr['code']));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}

	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query("DELETE FROM `gcms_shiraz_discount`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}

}   
    