<?php

/**
 * ShirazBooking.php
 *
 * This file is part of GCMS > MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: gcms_shiraz_booking
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */

class ShirazBooking
{

	public function __construct()
	{

	}

	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"INSERT INTO `gcms_shiraz_booking` (
				         `id`  , 
                         `id_user`  , 
                         `id_discount`  , 
                         `no`  , 
                         `pay`  , 
                         `date`  , 
                         `fr_name`  , 
                         `fr_email`  , 
                         `fr_cell` 
						) VALUES(
						 NULL  , 
                         %i  , 
                         %i  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n 
						)", array($arr['id_user'] , $arr['id_discount'] , $arr['no'] , $arr['pay'] , $arr['date'] , $arr['fr_name'] , $arr['fr_email'] , $arr['fr_cell']));
		return $GLOBALS['GCMS_DB']->query($query);
	}
    
    public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"UPDATE `gcms_shiraz_booking` SET
						 `id` =  %i 
                         [ , `id_user` = %I ] 
                         [ , `id_discount` = %I ] 
                         [ , `no` = %N ] 
                         [ , `pay` = %N ] 
                         [ , `date` = %N ] 
                         [ , `fr_name` = %N ] 
                         [ , `fr_email` = %N ] 
                         [ , `fr_cell` = %N ] 
                        
						WHERE `id` =  %i",
						array($arr['id'] , $arr['id_user'] , $arr['id_discount'] , $arr['no'] , $arr['pay'] , $arr['date'] , $arr['fr_name'] , $arr['fr_email'] , $arr['fr_cell'], $arr['id']));
		return $GLOBALS['GCMS_DB']->query($query);
	}

    public function get($arr, $list = false, $order = "" , $limit = "")
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT * FROM `gcms_shiraz_booking` WHERE TRUE
						 [ AND `id` = %I ] 
                         [ AND `id_user` = %I ] 
                         [ AND `id_discount` = %I ] 
                         [ AND `no` = %N ]
                         [ AND `pay` = %N ]
                         [ AND `date` = %N ]
                         [ AND `fr_name` = %N ]
                         [ AND `fr_email` = %N ]
                         [ AND `fr_cell` = %N ]
                        
						[ ORDER BY `%S` ] [ %S ] 
                        [ LIMIT %I ][ , %I ]
						",
						array($arr['id'] , $arr['id_user'] , $arr['id_discount'] , $arr['no'] , $arr['pay'] , $arr['date'] , $arr['fr_name'] , $arr['fr_email'] , $arr['fr_cell'], $order['by'], $order['sort'] ,$limit['start'],$limit['end']));
		if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}
    
    public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT COUNT(*) as Num FROM `gcms_shiraz_booking` WHERE TRUE
					    [ AND `id` = %I ] 
                         [ AND `id_user` = %I ] 
                         [ AND `id_discount` = %I ] 
                         [ AND `no` = %N ]
                         [ AND `pay` = %N ]
                         [ AND `date` = %N ]
                         [ AND `fr_name` = %N ]
                         [ AND `fr_email` = %N ]
                         [ AND `fr_cell` = %N ]
                        
						",
						array($arr['id'] , $arr['id_user'] , $arr['id_discount'] , $arr['no'] , $arr['pay'] , $arr['date'] , $arr['fr_name'] , $arr['fr_email'] , $arr['fr_cell']));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}

	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query("DELETE FROM `gcms_shiraz_booking`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}

}   
    