<?php

/**
 * Dinerorate.php
 *
 * This file is part of GCMS > MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: gcms_dinerorate
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */

class Dinerorate
{

	public function __construct()
	{

	}

	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"INSERT INTO `gcms_dinerorate` (
				         `id`  , 
                         `date`  , 
                         `ratebuy`  , 
                         `ratesell`  , 
                         `type`  , 
                         `refrence` 
						) VALUES(
						 NULL  , 
                         %n  , 
                         %i  , 
                         %i  , 
                         %n  , 
                         %n 
						)", array($arr['date'] , $arr['ratebuy'] , $arr['ratesell'] , $arr['type'] , $arr['refrence']));
				return $GLOBALS['GCMS_DB']->query($query);
	}
    
    public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"UPDATE `gcms_dinerorate` SET
						 `id` =  %i 
                         [ , `date` = %N ] 
                         [ , `ratebuy` = %I ] 
                         [ , `ratesell` = %I ] 
                         [ , `type` = %N ] 
                         [ , `refrence` = %N ] 
                        
						WHERE `id` =  %i",
						array($arr['id'] , $arr['date'] , $arr['ratebuy'] , $arr['ratesell'] , $arr['type'] , $arr['refrence'], $arr['id']));
		return $GLOBALS['GCMS_DB']->query($query);
	}

    public function get($arr, $list = false, $order = "" , $limit = "")
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT * FROM `gcms_dinerorate` WHERE TRUE
						 [ AND `id` = %I ] 
                         [ AND `date` = %N ]
                         [ AND `ratebuy` = %I ]
                         [ AND `ratesell` = %I ]
                         [ AND `type` = %N ]
                         [ AND `refrence` = %N ]
                        
						[ ORDER BY `%S` ] [ %S ] 
                        [ LIMIT %I ][ , %I ]
						",
						array($arr['id'] , $arr['date'] , $arr['ratebuy'] , $arr['ratesell'] , $arr['type'] , $arr['refrence'], $order['by'], $order['sort'] ,$limit['start'],$limit['end']));
		if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}
    
    public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT COUNT(*) as Num FROM `gcms_dinerorate` WHERE TRUE
					    [ AND `id` = %I ] 
                         [ AND `date` = %N ]
                         [ AND `ratebuy` = %I ]
                         [ AND `ratesell` = %I ]
                         [ AND `type` = %N ]
                         [ AND `refrence` = %N ]
                        
						",
						array($arr['id'] , $arr['date'] , $arr['ratebuy'] , $arr['ratesell'] , $arr['type'] , $arr['refrence']));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}

	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query("DELETE FROM `gcms_dinerorate`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}

}   
    