<?php

/**
 * Dineroadv.php
 *
 * This file is part of GCMS > MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: gcms_dineroadv
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */

class Dineroadv
{

	public function __construct()
	{

	}

	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"INSERT INTO `gcms_dineroadv` (
				         `id`  , 
                         `id_user`  , 
                         `currency`  , 
                         `amount`  , 
                         `minmax`  , 
                         `locations`  , 
                         `method`  , 
                         `status`  , 
                         `text`  , 
                         `time` 
						) VALUES(
						 NULL  , 
                         %i  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n 
						)", array($arr['id_user'] , $arr['currency'] , $arr['amount'] , $arr['minmax'] , $arr['locations'] , $arr['method'] , $arr['status'] , $arr['text'] , $arr['time']));
		return $GLOBALS['GCMS_DB']->query($query);
	}
    
    public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"UPDATE `gcms_dineroadv` SET
						 `id` =  %i 
                         [ , `id_user` = %I ] 
                         [ , `currency` = %N ] 
                         [ , `amount` = %N ] 
                         [ , `minmax` = %N ] 
                         [ , `locations` = %N ] 
                         [ , `method` = %N ] 
                         [ , `status` = %N ] 
                         [ , `text` = %N ] 
                         [ , `time` = %N ] 
                        
						WHERE `id` =  %i",
						array($arr['id'] , $arr['id_user'] , $arr['currency'] , $arr['amount'] , $arr['minmax'] , $arr['locations'] , $arr['method'] , $arr['status'] , $arr['text'] , $arr['time'], $arr['id']));
		return $GLOBALS['GCMS_DB']->query($query);
	}

    public function get($arr, $list = false, $order = "" , $limit = "")
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT * FROM `gcms_dineroadv` WHERE TRUE
						 [ AND `id` = %I ] 
                         [ AND `id_user` = %I ] 
                         [ AND `currency` = %N ]
                         [ AND `amount` = %N ]
                         [ AND `minmax` = %N ]
                         [ AND `locations` = %N ]
                         [ AND `method` = %N ]
                         [ AND `status` = %N ]
                         [ AND `text` = %N ]
                         [ AND `time` = %N ]
                        
						[ ORDER BY `%S` ] [ %S ] 
                        [ LIMIT %I ][ , %I ]
						",
						array($arr['id'] , $arr['id_user'] , $arr['currency'] , $arr['amount'] , $arr['minmax'] , $arr['locations'] , $arr['method'] , $arr['status'] , $arr['text'] , $arr['time'], $order['by'], $order['sort'] ,$limit['start'],$limit['end']));
		if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}
    
    public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT COUNT(*) as Num FROM `gcms_dineroadv` WHERE TRUE
					    [ AND `id` = %I ] 
                         [ AND `id_user` = %I ] 
                         [ AND `currency` = %N ]
                         [ AND `amount` = %N ]
                         [ AND `minmax` = %N ]
                         [ AND `locations` = %N ]
                         [ AND `method` = %N ]
                         [ AND `status` = %N ]
                         [ AND `text` = %N ]
                         [ AND `time` = %N ]
                        
						",
						array($arr['id'] , $arr['id_user'] , $arr['currency'] , $arr['amount'] , $arr['minmax'] , $arr['locations'] , $arr['method'] , $arr['status'] , $arr['text'] , $arr['time']));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}

	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query("DELETE FROM `gcms_dineroadv`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}

}   
    