<?php

/**
 * Wallettransactions.php
 *
 * This file is part of GCMS > MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: gcms_wallettransactions
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */

class Wallettransactions
{

	public function __construct()
	{

	}

	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"INSERT INTO `gcms_wallettransactions` (
				         `id`  , 
                         `id_wallet`  , 
                         `type`  , 
                         `amount`  , 
                         `status`  , 
                         `text`  , 
                         `time` 
						) VALUES(
						 NULL  , 
                         %i  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n 
						)", array($arr['id_wallet'] , $arr['type'] , $arr['amount'] , $arr['status'] , $arr['text'] , $arr['time']));
		$GLOBALS['GCMS_DB']->query($query);
		return mysql_insert_id();
	}
    
    public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"UPDATE `gcms_wallettransactions` SET
						 `id` =  %i 
                         [ , `id_wallet` = %I ] 
                         [ , `type` = %N ] 
                         [ , `amount` = %N ] 
                         [ , `status` = %N ] 
                         [ , `text` = %N ] 
                         [ , `time` = %N ] 
                        
						WHERE `id` =  %i",
						array($arr['id'] , $arr['id_wallet'] , $arr['type'] , $arr['amount'] , $arr['status'] , $arr['text'] , $arr['time'], $arr['id']));
		return $GLOBALS['GCMS_DB']->query($query);
	}

    public function get($arr, $list = false, $order = "" , $limit = "")
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT * FROM `gcms_wallettransactions` WHERE TRUE
						 [ AND `id` = %I ] 
                         [ AND `id_wallet` = %I ] 
                         [ AND `type` = %N ]
                         [ AND `amount` = %N ]
                         [ AND `status` = %N ]
                         [ AND `text` = %N ]
                         [ AND `time` = %N ]
                        
						[ ORDER BY `%S` ] [ %S ] 
                        [ LIMIT %I ][ , %I ]
						",
						array($arr['id'] , $arr['id_wallet'] , $arr['type'] , $arr['amount'] , $arr['status'] , $arr['text'] , $arr['time'], $order['by'], $order['sort'] ,$limit['start'],$limit['end']));
		if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}
    
    public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT COUNT(*) as Num FROM `gcms_wallettransactions` WHERE TRUE
					    [ AND `id` = %I ] 
                         [ AND `id_wallet` = %I ] 
                         [ AND `type` = %N ]
                         [ AND `amount` = %N ]
                         [ AND `status` = %N ]
                         [ AND `text` = %N ]
                         [ AND `time` = %N ]
                        
						",
						array($arr['id'] , $arr['id_wallet'] , $arr['type'] , $arr['amount'] , $arr['status'] , $arr['text'] , $arr['time']));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}

	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query("DELETE FROM `gcms_wallettransactions`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}

}   
    