<?php
/**
 * Sarfejo_user.php
 *
 * This file is part of GCMS > MODULE MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB:
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */


class Sarfejo_user
{

	public function __construct()
	{
	
	}
	
	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
		->query(
				"INSERT INTO `gcms_sarfejo_user` (
				         `id`  ,
                         `email`  ,
                         `temp_code`  ,
                         `password`  ,
                         `password_salt`  ,
                         `gender`  ,
                         `level`  ,
                         `status`  ,
                         `cell`  ,
                         `name`  ,
                         `birthdate`  ,
                         `state`  ,
                         `city`  ,
                         `co_name`  ,
                         `degree`  ,
                         `credit`  ,
                         `address`  ,
                         `avatar`  ,
                         `created_date`
						) VALUES(
						 NULL  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n
						)", array($arr['email'] , $arr['temp_code'] , $arr['password'] , $arr['password_salt'] , $arr['gender'] , $arr['level'] , $arr['status'] , $arr['cell'] , $arr['name'] , $arr['birthdate'] , $arr['state'] , $arr['city'] , $arr['co_name'] , $arr['degree'] , $arr['credit'] , $arr['address'] , $arr['avatar'] , $arr['created_date']));
		return $GLOBALS['GCMS_DB']->query($query);
	}
	
	public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
		->query(
				"UPDATE `gcms_sarfejo_user` SET
						 `id` =  %i
                         [ , `email` = %N ]
                         [ , `temp_code` = %N ]
                         [ , `password` = %N ]
                         [ , `password_salt` = %N ]
                         [ , `gender` = %N ]
                         [ , `level` = %N ]
                         [ , `status` = %N ]
                         [ , `cell` = %N ]
                         [ , `name` = %N ]
                         [ , `birthdate` = %N ]
                         [ , `state` = %N ]
                         [ , `city` = %N ]
                         [ , `co_name` = %N ]
                         [ , `degree` = %N ]
                         [ , `credit` = %N ]
                         [ , `address` = %N ]
                         [ , `avatar` = %N ]
                         [ , `created_date` = %N ]
	
						WHERE `id` =  %i",
				array($arr['id'] , $arr['email'] , $arr['temp_code'] , $arr['password'] , $arr['password_salt'] , $arr['gender'] , $arr['level'] , $arr['status'] , $arr['cell'] , $arr['name'] , $arr['birthdate'] , $arr['state'] , $arr['city'] , $arr['co_name'] , $arr['degree'] , $arr['credit'] ,$arr['address'] , $arr['avatar'] , $arr['created_date'], $arr['id']));
		return $GLOBALS['GCMS_DB']->query($query);
	}
	
	public function get($arr, $list = false, $order = "" , $limit = "")
	{
		$query=$GLOBALS['GCMS_SAFESQL']
		->query(
				"SELECT * FROM `gcms_sarfejo_user` WHERE TRUE
						 [ AND `id` = %I ]
                         [ AND `email` = %N ]
                         [ AND `temp_code` = %N ]
                         [ AND `password` = %N ]
                         [ AND `password_salt` = %N ]
                         [ AND `gender` = %N ]
                         [ AND `level` = %N ]
                         [ AND `status` = %N ]
                         [ AND `cell` = %N ]
                         [ AND `name` = %N ]
                         [ AND `birthdate` = %N ]
                         [ AND `state` = %N ]
                         [ AND `city` = %N ]
                         [ AND `co_name` = %N ]
                         [ AND `degree` = %N ]
                         [ AND `credit` = %N ]
                         [ AND `address` = %N ]
                         [ AND `avatar` = %N ]
                         [ AND `created_date` = %N ]
						 [ AND (`name` LIKE %N OR `email` LIKE %N )]
	
						[ ORDER BY `%S` ] [ %S ]
                        [ LIMIT %I ][ , %I ]
						",
				array($arr['id'] , $arr['email'] , $arr['temp_code'] , $arr['password'] , $arr['password_salt'] , $arr['gender'] , $arr['level'] , $arr['status'] , $arr['cell'] , $arr['name'] , $arr['birthdate'] , $arr['state'] , $arr['city'] , $arr['co_name'] , $arr['degree'] , $arr['credit'] ,$arr['address'] , $arr['avatar'] , $arr['created_date'], $arr['search'], $arr['search'], $order['by'], $order['sort'] ,$limit['start'],$limit['end']));
		if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}
	
	public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
		->query(
				"SELECT COUNT(*) as Num FROM `gcms_sarfejo_user` WHERE TRUE
					    [ AND `id` = %I ]
                         [ AND `email` = %N ]
                         [ AND `temp_code` = %N ]
                         [ AND `password` = %N ]
                         [ AND `password_salt` = %N ]
                         [ AND `gender` = %N ]
                         [ AND `level` = %N ]
                         [ AND `status` = %N ]
                         [ AND `cell` = %N ]
                         [ AND `name` = %N ]
                         [ AND `birthdate` = %N ]
                         [ AND `state` = %N ]
                         [ AND `city` = %N ]
                         [ AND `co_name` = %N ]
                         [ AND `degree` = %N ]
                         [ AND `credit` = %N ]
                         [ AND `address` = %N ]
                         [ AND `avatar` = %N ]
                         [ AND `created_date` = %N ]
						 [ AND (`name` LIKE %N OR `email` LIKE %N )]
	
						",
				array($arr['id'] , $arr['email'] , $arr['temp_code'] , $arr['password'] , $arr['password_salt'] , $arr['gender'] , $arr['level'] , $arr['status'] , $arr['cell'] , $arr['name'] , $arr['birthdate'] , $arr['state'] , $arr['city'] , $arr['co_name'] , $arr['degree'] , $arr['credit'] , $arr['address'] , $arr['avatar'] , $arr['created_date'], $arr['search'], $arr['search']));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}
	
	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
		->query("DELETE FROM `gcms_sarfejo_user`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}
	
}
