<?php
/**
 * Contract.php
 *
 * This file is part of GCMS > MODULE MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: gcms_contract
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */

require_once(__COREROOT__."/module/contract/model/Domains.php");

class Contract
{

	public function __construct()
	{

	}

	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"INSERT INTO `gcms_contract` (
				         `id`  , 
                         `id_user`  , 
                         `title`  , 
                         `content`  , 
                         `date`  , 
                         `support_status`  , 
                         `support_type`  , 
                         `host_title`  , 
                         `host_text`  , 
                         `host_exp_date`  , 
                         `contract_status`  , 
                         `contract_type`  , 
                         `contract_duration`  , 
                         `contract_fee`  , 
                         `contract_pay_type` 
						) VALUES(
						 NULL  , 
                         %i  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n 
						)", array($arr['id_user'] , $arr['title'] , $arr['content'] , $arr['date'] , $arr['support_status'] , $arr['support_type'] , $arr['host_title'] , $arr['host_text'] , $arr['host_exp_date'] , $arr['contract_status'] , $arr['contract_type'] , $arr['contract_duration'] , $arr['contract_fee'] , $arr['contract_pay_type']));
		return $GLOBALS['GCMS_DB']->query($query);
	}
    
    public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"UPDATE `gcms_contract` SET
						 `id` =  %i 
                         [ , `id_user` = %I ] 
                         [ , `title` = %N ] 
                         [ , `content` = %N ] 
                         [ , `date` = %N ] 
                         [ , `support_status` = %N ] 
                         [ , `support_type` = %N ] 
                         [ , `host_title` = %N ] 
                         [ , `host_text` = %N ] 
                         [ , `host_exp_date` = %N ] 
                         [ , `contract_status` = %N ] 
                         [ , `contract_type` = %N ] 
                         [ , `contract_duration` = %N ] 
                         [ , `contract_fee` = %N ] 
                         [ , `contract_pay_type` = %N ] 
                        
						WHERE `id` =  %i",
						array($arr['id'] , $arr['id_user'] , $arr['title'] , $arr['content'] , $arr['date'] , $arr['support_status'] , $arr['support_type'] , $arr['host_title'] , $arr['host_text'] , $arr['host_exp_date'] , $arr['contract_status'] , $arr['contract_type'] , $arr['contract_duration'] , $arr['contract_fee'] , $arr['contract_pay_type'], $arr['id']));
		return $GLOBALS['GCMS_DB']->query($query);
	}

    public function get($arr, $list = false, $order = "" , $limit = "")
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT * FROM `gcms_contract` WHERE TRUE
						 [ AND `id` = %I ] 
                         [ AND `id_user` = %I ] 
                         [ AND `title` = %N ]
                         [ AND `content` = %N ]
                         [ AND `date` = %N ]
                         [ AND `support_status` = %N ]
                         [ AND `support_type` = %N ]
                         [ AND `host_title` = %N ]
                         [ AND `host_text` = %N ]
                         [ AND `host_exp_date` = %N ]
                         [ AND `contract_status` = %N ]
                         [ AND `contract_type` = %N ]
                         [ AND `contract_duration` = %N ]
                         [ AND `contract_fee` = %N ]
                         [ AND `contract_pay_type` = %N ]
                        [ AND (`content` LIKE %N OR `date` LIKE %N )]
						[ ORDER BY `%S` ] [ %S ] 
                        [ LIMIT %I ][ , %I ]
						",
						array($arr['id'] , $arr['id_user'] , $arr['title'] , $arr['content'] , $arr['date'] , $arr['support_status'] , $arr['support_type'] , $arr['host_title'] , $arr['host_text'] , $arr['host_exp_date'] , $arr['contract_status'] , $arr['contract_type'] , $arr['contract_duration'] , $arr['contract_fee'] , $arr['contract_pay_type'],
                         $arr['search'],
						$arr['search'],
                         $order['by'], $order['sort'] ,$limit['start'],$limit['end']));
		if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}
    
    public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT COUNT(*) as Num FROM `gcms_contract` WHERE TRUE
					    [ AND `id` = %I ] 
                         [ AND `id_user` = %I ] 
                         [ AND `title` = %N ]
                         [ AND `content` = %N ]
                         [ AND `date` = %N ]
                         [ AND `support_status` = %N ]
                         [ AND `support_type` = %N ]
                         [ AND `host_title` = %N ]
                         [ AND `host_text` = %N ]
                         [ AND `host_exp_date` = %N ]
                         [ AND `contract_status` = %N ]
                         [ AND `contract_type` = %N ]
                         [ AND `contract_duration` = %N ]
                         [ AND `contract_fee` = %N ]
                         [ AND `contract_pay_type` = %N ]
                         [ AND (`content` LIKE %N OR `date` LIKE %N )]
						",
						array($arr['id'] , $arr['id_user'] , $arr['title'] , $arr['content'] , $arr['date'] , $arr['support_status'] , $arr['support_type'] , $arr['host_title'] , $arr['host_text'] , $arr['host_exp_date'] , $arr['contract_status'] , $arr['contract_type'] , $arr['contract_duration'] , $arr['contract_fee'] 
                        , $arr['contract_pay_type'],
                        $arr['search'],
						$arr['search']
                        ));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}

	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query("DELETE FROM `gcms_contract`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}

}   
    