<?php

/**
 * Products.php
 *
 * This file is part of GCMS > MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: gcms_products
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */

class Products
{

	public function __construct()
	{

	}

	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"INSERT INTO `gcms_products` (
				         `id`  , 
                         `group_id`  , 
                         `brand`  , 
                         `color`  , 
                         `size`  , 
                         `en_title`  , 
                         `fa_title`  , 
                         `en_txt`  , 
                         `fa_txt`  , 
                         `delivery_time`  , 
                         `link`  , 
                         `update_check`  , 
                         `buy_price`  , 
                         `real_price`  , 
                         `price`  , 
                         `salse1_price`  , 
                         `sales2_price`  , 
                         `min_price`  , 
                         `quantity`  , 
                         `visitor`  , 
                         `p_order`  , 
                         `show_real_price`  , 
                         `show_sales_price`  , 
                         `status`  , 
                         `barcode`  , 
                         `refrence`  , 
                         `default_photo` 
						) VALUES(
						 NULL  , 
                         %i  , 
                         %i  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n 
						)", array($arr['group_id'] , $arr['brand'] , $arr['color'] , $arr['size'] , $arr['en_title'] , $arr['fa_title'] , $arr['en_txt'] , $arr['fa_txt'] , $arr['delivery_time'] , $arr['link'] , $arr['update_check'] , $arr['buy_price'] , $arr['real_price'] , $arr['price'] , $arr['salse1_price'] , $arr['sales2_price'] , $arr['min_price'] , $arr['quantity'] , $arr['visitor'] , $arr['p_order'] , $arr['show_real_price'] , $arr['show_sales_price'] , $arr['status'] , $arr['barcode'], $arr['refrence'] , $arr['default_photo']));
		if ($GLOBALS['GCMS_DB']->query($query)){
			return $GLOBALS['GCMS_DB']->insert_id;
		}else{
			return 0;
		}
	}
    
    public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"UPDATE `gcms_products` SET
						 `id` =  %i 
                         [ , `group_id` = %I ] 
                         [ , `brand` = %I ] 
                         [ , `color` = %N ] 
                         [ , `size` = %N ] 
                         [ , `en_title` = %N ] 
                         [ , `fa_title` = %N ] 
                         [ , `en_txt` = %N ] 
                         [ , `fa_txt` = %N ] 
                         [ , `delivery_time` = %N ] 
                         [ , `link` = %N ] 
                         [ , `update_check` = %N ] 
                         [ , `buy_price` = %N ] 
                         [ , `real_price` = %N ] 
                         [ , `price` = %N ] 
                         [ , `salse1_price` = %N ] 
                         [ , `sales2_price` = %N ] 
                         [ , `min_price` = %N ] 
                         [ , `quantity` = %N ] 
                         [ , `visitor` = %N ] 
                         [ , `p_order` = %N ] 
                         [ , `show_real_price` = %N ] 
                         [ , `show_sales_price` = %N ] 
                         [ , `status` = %N ] 
                         [ , `barcode` = %N ] 
                         [ , `refrence` = %N ] 
                         [ , `default_photo` = %N ] 
                        
						WHERE `id` =  %i",
						array($arr['id'] , $arr['group_id'] , $arr['brand'] , $arr['color'] , $arr['size'] , $arr['en_title'] , $arr['fa_title'] , $arr['en_txt'] , $arr['fa_txt'] , $arr['delivery_time'] , $arr['link'] , $arr['update_check'] , $arr['buy_price'] , $arr['real_price'] , $arr['price'] , $arr['salse1_price'] , $arr['sales2_price'], $arr['min_price'] , $arr['quantity'] , $arr['visitor'] , $arr['p_order'] , $arr['show_real_price'] , $arr['show_sales_price'] , $arr['status'] , $arr['barcode'], $arr['refrence'] , $arr['default_photo'], $arr['id']));
		return $GLOBALS['GCMS_DB']->query($query);
	}

    public function get($arr, $list = false, $order = "" , $limit = "")
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT * FROM `gcms_products` WHERE TRUE
						 [ AND `id` = %I ] 
                         [ AND `group_id` = %I ] 
                         [ AND `brand` = %I ] 
                         [ AND `color` = %N ] 
                         [ AND `size` = %N ] 
                         [ AND `en_title` = %N ]
                         [ AND `fa_title` = %N ]
                         [ AND `en_txt` = %N ]
                         [ AND `fa_txt` = %N ]
                         [ AND `delivery_time` = %N ]
                         [ AND `link` = %N ]
                         [ AND `update_check` = %N ]
                         [ AND `buy_price` = %N ]
                         [ AND `real_price` = %N ]
                         [ AND `price` = %N ]
                         [ AND `salse1_price` = %N ]
                         [ AND `sales2_price` = %N ]
                         [ AND `min_price` = %N ]
                         [ AND `quantity` = %N ]
                         [ AND `visitor` = %N ]
                         [ AND `p_order` = %N ]
                         [ AND `show_real_price` = %N ]
                         [ AND `show_sales_price` = %N ]
                         [ AND `status` = %N ]
                         [ AND `barcode` = %N ]
                         [ AND `refrence` = %N ]
                         [ AND `default_photo` = %N ]
                        [ AND (`en_title` LIKE %N OR `fa_title` LIKE %N )]
						
						[ ORDER BY `%S` ] [ %S ] 
                        [ LIMIT %I ][ , %I ]
						",
						array($arr['id'] ,  $arr['group_id'] , $arr['brand'] , $arr['color'] , $arr['size'] , $arr['en_title'] , $arr['fa_title'] , $arr['en_txt'] , $arr['fa_txt'] , $arr['delivery_time'] , $arr['link'] , $arr['update_check'] , $arr['buy_price'] , $arr['real_price'] , $arr['price'] , $arr['salse1_price'] , $arr['sales2_price'] , $arr['min_price'] , $arr['quantity'] , $arr['visitor'] , $arr['p_order'] , $arr['show_real_price'] , $arr['show_sales_price'] , $arr['status'] , $arr['barcode'], $arr['refrence'] , $arr['default_photo'], $arr['search'], $arr['search'],$order['by'], $order['sort'] ,$limit['start'],$limit['end']));
		if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}
    
    public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT COUNT(*) as Num FROM `gcms_products` WHERE TRUE
					    [ AND `id` = %I ] 
                         [ AND `group_id` = %I ] 
                         [ AND `brand` = %I ] 
                         [ AND `color` = %N ] 
                         [ AND `size` = %N ] 
                         [ AND `en_title` = %N ]
                         [ AND `fa_title` = %N ]
                         [ AND `en_txt` = %N ]
                         [ AND `fa_txt` = %N ]
                         [ AND `delivery_time` = %N ]
                         [ AND `link` = %N ]
                         [ AND `update_check` = %N ]
                         [ AND `buy_price` = %N ]
                         [ AND `real_price` = %N ]
                         [ AND `price` = %N ]
                         [ AND `salse1_price` = %N ]
                         [ AND `sales2_price` = %N ]
                         [ AND `min_price` = %N ]
                         [ AND `quantity` = %N ]
                         [ AND `visitor` = %N ]
                         [ AND `p_order` = %N ]
                         [ AND `show_real_price` = %N ]
                         [ AND `show_sales_price` = %N ]
                         [ AND `status` = %N ]
                         [ AND `barcode` = %N ]
                         [ AND `refrence` = %N ]
                         [ AND `default_photo` = %N ]
                        
						",
						array($arr['id'] , $arr['group_id'] , $arr['brand'] , $arr['color'] , $arr['size'] , $arr['en_title'] , $arr['fa_title'] , $arr['en_txt'] , $arr['fa_txt'] , $arr['delivery_time'] , $arr['link'] , $arr['update_check'] , $arr['buy_price'] , $arr['real_price'] , $arr['price'] , $arr['salse1_price'] , $arr['sales2_price'] , $arr['min_price'] , $arr['quantity'] , $arr['visitor'] , $arr['p_order'] , $arr['show_real_price'] , $arr['show_sales_price'] , $arr['status'] , $arr['barcode'], $arr['refrence'] , $arr['default_photo']));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}

	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query("DELETE FROM `gcms_products`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}

}   
    