<?php

/**
 * AccountKit.php
 *
 * This file is part of GCMS > MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: gcms_accountKit
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */

class AccountKit
{

	public function __construct()
	{

	}

	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"INSERT INTO `gcms_accountKit` (
				         `id`  , 
                         `email`  , 
                         `number`  , 
                         `status`  , 
                         `level` 
						) VALUES(
						 NULL  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n 
						)", array($arr['email'] , $arr['number'] , $arr['status'] , $arr['level']));
		return $GLOBALS['GCMS_DB']->query($query);
	}
    
    public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"UPDATE `gcms_accountKit` SET
						 `id` =  %i 
                         [ , `email` = %N ] 
                         [ , `number` = %N ] 
                         [ , `status` = %N ] 
                         [ , `level` = %N ] 
                        
						WHERE `id` =  %i",
						array($arr['id'] , $arr['email'] , $arr['number'] , $arr['status'] , $arr['level'], $arr['id']));
		return $GLOBALS['GCMS_DB']->query($query);
	}

    public function get($arr, $list = false, $order = "" , $limit = "")
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT * FROM `gcms_accountKit` WHERE TRUE
						 [ AND `id` = %I ] 
                         [ AND `email` = %N ]
                         [ AND `number` = %N ]
                         [ AND `status` = %N ]
                         [ AND `level` = %N ]
                        
						[ ORDER BY `%S` ] [ %S ] 
                        [ LIMIT %I ][ , %I ]
						",
						array($arr['id'] , $arr['email'] , $arr['number'] , $arr['status'] , $arr['level'], $order['by'], $order['sort'] ,$limit['start'],$limit['end']));
		if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}
    
    public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT COUNT(*) as Num FROM `gcms_accountKit` WHERE TRUE
					    [ AND `id` = %I ] 
                         [ AND `email` = %N ]
                         [ AND `number` = %N ]
                         [ AND `status` = %N ]
                         [ AND `level` = %N ]
                        
						",
						array($arr['id'] , $arr['email'] , $arr['number'] , $arr['status'] , $arr['level']));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}

	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query("DELETE FROM `gcms_accountKit`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}

}   
    