<?php
/**
 * Khodro.php
 *
 * This file is part of GCMS > MODULE MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: 
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */
require_once(__COREROOT__."/module/khodro/model/KhodroAdver.php");
require_once(__COREROOT__."/module/khodro/model/KhodroBrand.php");
require_once(__COREROOT__."/module/khodro/model/KhodroMessage.php");
require_once(__COREROOT__."/module/khodro/model/KhodroModel.php");
require_once(__COREROOT__."/module/khodro/model/KhodroPay.php");
require_once(__COREROOT__."/module/khodro/model/KhodroSearch.php");
require_once(__COREROOT__."/module/khodro/model/KhodroTip.php");
require_once(__COREROOT__."/module/khodro/model/KhodroUser.php");
require_once(__COREROOT__."/module/khodro/model/KhodroUsercost.php");
class Khodro
{

	public function __construct()
	{

	}
}
