<?php

/**
 * KhodroUsercost.php
 *
 * This file is part of GCMS > MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: gcms_khodro_usercost
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */

class KhodroUsercost
{

	public function __construct()
	{

	}

	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"INSERT INTO `gcms_khodro_usercost` (
				         `id`  , 
                         `id_user`  , 
                         `cost_name`  , 
                         `cost_fee`  , 
                         `cost_text`  , 
                         `cost_date` 
						) VALUES(
						 NULL  , 
                         %i  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n 
						)", array($arr['id_user'] , $arr['cost_name'] , $arr['cost_fee'] , $arr['cost_text'] , $arr['cost_date']));
		return $GLOBALS['GCMS_DB']->query($query);
	}
    
    public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"UPDATE `gcms_khodro_usercost` SET
						 `id` =  %i 
                         [ , `id_user` = %I ] 
                         [ , `cost_name` = %N ] 
                         [ , `cost_fee` = %N ] 
                         [ , `cost_text` = %N ] 
                         [ , `cost_date` = %N ] 
                        
						WHERE `id` =  %i",
						array($arr['id'] , $arr['id_user'] , $arr['cost_name'] , $arr['cost_fee'] , $arr['cost_text'] , $arr['cost_date'],$arr['id'] ));
		return $GLOBALS['GCMS_DB']->query($query);
	}

    public function get($arr, $list = false, $order = "" , $limit = "")
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT * FROM `gcms_khodro_usercost` WHERE TRUE
						 [ AND `id` = %I ] 
                         [ AND `id_user` = %I ] 
                         [ AND `cost_name` = %N ]
                         [ AND `cost_fee` = %N ]
                         [ AND `cost_text` = %N ]
                         [ AND `cost_date` = %N ]
                        
						[ ORDER BY `%S` ] [ %S ] 
                        [ LIMIT %I ][ , %I ]
						",
						array($arr['id'] , $arr['id_user'] , $arr['cost_name'] , $arr['cost_fee'] , $arr['cost_text'] , $arr['cost_date'], $order['by'], $order['sort'] ,$limit['start'],$limit['end']));
		if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}
    
    public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT COUNT(*) as Num FROM `gcms_khodro_usercost` WHERE TRUE
					    [ AND `id` = %I ] 
                         [ AND `id_user` = %I ] 
                         [ AND `cost_name` = %N ]
                         [ AND `cost_fee` = %N ]
                         [ AND `cost_text` = %N ]
                         [ AND `cost_date` = %N ]
                        
						",
						array($arr['id'] , $arr['id_user'] , $arr['cost_name'] , $arr['cost_fee'] , $arr['cost_text'] , $arr['cost_date']));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}

	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query("DELETE FROM `gcms_khodro_usercost`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}

}   
    