<?php

/**
 * KhodroUser.php
 *
 * This file is part of GCMS > MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: gcms_khodro_user
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */

class KhodroUser
{

	public function __construct()
	{

	}

	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"INSERT INTO `gcms_khodro_user` (
				         `id`  ,
                         `name`  ,
                         `office_name`  ,
                         `email`  ,
                         `cell`  ,
                         `tell`  ,
                         `fax`  ,
                         `address`  ,
                         `cell_vrfy`  ,
                         `password`  ,
                         `password_salt`  ,
                         `password_temp_code`  ,
                         `user_status`  ,
                         `user_type`  ,
                         `created_date` ,
                         `admin_txt` ,
                         `label`,
                         `res_list`
						) VALUES(
						 NULL  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n
						)", array($arr['name'] , $arr['office_name'] , $arr['email'] , $arr['cell'] , $arr['tell'] , $arr['fax'] , $arr['address'] , $arr['cell_vrfy'] , $arr['password'] , $arr['password_salt'] , $arr['password_temp_code'] , $arr['user_status'] , $arr['user_type'] , $arr['created_date'], $arr['admin_txt'], $arr['label'], $arr['res_list']));
		return $GLOBALS['GCMS_DB']->query($query);
	}

    public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"UPDATE `gcms_khodro_user` SET
						 `id` =  %i
                         [ , `name` = %N ]
                         [ , `office_name` = %N ]
                         [ , `email` = %N ]
                         [ , `cell` = %N ]
                         [ , `tell` = %N ]
                         [ , `fax` = %N ]
                         [ , `address` = %N ]
                         [ , `cell_vrfy` = %N ]
                         [ , `password` = %N ]
                         [ , `password_salt` = %N ]
                         [ , `password_temp_code` = %N ]
                         [ , `user_status` = %N ]
                         [ , `user_type` = %N ]
                         [ , `created_date` = %N ]
						 [ , `admin_txt` = %N ]
						 [ , `label` = %N ]
						 [ , `res_list` = %N ]
						WHERE `id` =  %i",
						array($arr['id'] , $arr['name'] , $arr['office_name'] , $arr['email'] , $arr['cell'] , $arr['tell'] , $arr['fax'] , $arr['address'] , $arr['cell_vrfy'] , $arr['password'] , $arr['password_salt'] , $arr['password_temp_code'] , $arr['user_status'] , $arr['user_type'] , $arr['created_date'], $arr['admin_txt'], $arr['label'], $arr['res_list'],$arr['id'] ));
		return $GLOBALS['GCMS_DB']->query($query);
	}

    public function get($arr, $list = false, $order = "" , $limit = "")
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT * FROM `gcms_khodro_user` WHERE TRUE
						 [ AND `id` = %I ]
                         [ AND `name` = %N ]
                         [ AND `office_name` = %N ]
                         [ AND `email` = %N ]
                         [ AND `cell` = %N ]
                         [ AND `tell` = %N ]
                         [ AND `fax` = %N ]
                         [ AND `address` = %N ]
                         [ AND `cell_vrfy` = %N ]
                         [ AND `password` = %N ]
                         [ AND `password_salt` = %N ]
                         [ AND `password_temp_code` = %N ]
                         [ AND `user_status` = %N ]
                         [ AND `user_type` = %N ]
                         [ AND `created_date` = %N ]
                         [ AND `admin_txt` = %N ]
                         [ AND `label` = %N ]
                         [ AND `res_list` = %N ]
                        [ AND (`name` LIKE %N OR `email` LIKE %N )]
						[ ORDER BY `%S` ] [ %S ]
                        [ LIMIT %I ][ , %I ]
						",
						array($arr['id'] , $arr['name'] , $arr['office_name'] , $arr['email'] , $arr['cell'] , $arr['tell'] , $arr['fax'] , $arr['address'] , $arr['cell_vrfy'] , $arr['password'] , $arr['password_salt'] , $arr['password_temp_code'] , $arr['user_status'] , $arr['user_type'] , $arr['created_date'],$arr['admin_txt'],$arr['label'],$arr['res_list'],
                        $arr['search'],$arr['search'],
                         $order['by'], $order['sort'] ,$limit['start'],$limit['end']));
		if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}

    public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT COUNT(*) as Num FROM `gcms_khodro_user` WHERE TRUE
					    [ AND `id` = %I ]
                         [ AND `name` = %N ]
                         [ AND `office_name` = %N ]
                         [ AND `email` = %N ]
                         [ AND `cell` = %N ]
                         [ AND `tell` = %N ]
                         [ AND `fax` = %N ]
                         [ AND `address` = %N ]
                         [ AND `cell_vrfy` = %N ]
                         [ AND `password` = %N ]
                         [ AND `password_salt` = %N ]
                         [ AND `password_temp_code` = %N ]
                         [ AND `user_status` = %N ]
                         [ AND `user_type` = %N ]
                         [ AND `created_date` = %N ]
                         [ AND `admin_txt` = %N ]
                         [ AND `label` = %N ]
                         [ AND `res_list` = %N ]
                        [ AND (`name` LIKE %N OR `email` LIKE %N )]

						",
						array($arr['id'] , $arr['name'] , $arr['office_name'] , $arr['email'] , $arr['cell'] , $arr['tell'] , $arr['fax'] , $arr['address'] , $arr['cell_vrfy'] , $arr['password'] , $arr['password_salt'] , $arr['password_temp_code'] , $arr['user_status'] , $arr['user_type'] , $arr['created_date'],$arr['admin_txt'],$arr['label'],$arr['res_list'],
                        $arr['search'],$arr['search']
                        ));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}

	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query("DELETE FROM `gcms_khodro_user`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}

}
