<?php

/**
 * KhodroPay.php
 *
 * This file is part of GCMS > MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: gcms_khodro_pay
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */

class KhodroPay
{

	public function __construct()
	{

	}

	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"INSERT INTO `gcms_khodro_pay` (
				         `id`  , 
                         `id_user`  , 
                         `pay_fee`  , 
                         `pay_title`  , 
                         `pay_text`  , 
                         `bank_info`  , 
                         `pay_status`  , 
                         `pay_type`  , 
                         `pay_date` 
						) VALUES(
						 NULL  , 
                         %i  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n 
						)", array($arr['id_user'] , $arr['pay_fee'] , $arr['pay_title'] , $arr['pay_text'] , $arr['bank_info'] , $arr['pay_status'] , $arr['pay_type'] , $arr['pay_date']));
		return $GLOBALS['GCMS_DB']->query($query);
	}
    
    public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"UPDATE `gcms_khodro_pay` SET
						 `id` =  %i 
                         [ , `id_user` = %I ] 
                         [ , `pay_fee` = %N ] 
                         [ , `pay_title` = %N ] 
                         [ , `pay_text` = %N ] 
                         [ , `bank_info` = %N ] 
                         [ , `pay_status` = %N ] 
                         [ , `pay_type` = %N ] 
                         [ , `pay_date` = %N ] 
                        
						WHERE `id` =  %i",
						array($arr['id'] , $arr['id_user'] , $arr['pay_fee'] , $arr['pay_title'] , $arr['pay_text'] , $arr['bank_info'] , $arr['pay_status'] , $arr['pay_type'] , $arr['pay_date'],$arr['id'] ));
		return $GLOBALS['GCMS_DB']->query($query);
	}

    public function get($arr, $list = false, $order = "" , $limit = "")
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT * FROM `gcms_khodro_pay` WHERE TRUE
						 [ AND `id` = %I ] 
                         [ AND `id_user` = %I ] 
                         [ AND `pay_fee` = %N ]
                         [ AND `pay_title` = %N ]
                         [ AND `pay_text` = %N ]
                         [ AND `bank_info` = %N ]
                         [ AND `pay_status` = %N ]
                         [ AND `pay_type` = %N ]
                         [ AND `pay_date` = %N ]
                        
						[ ORDER BY `%S` ] [ %S ] 
                        [ LIMIT %I ][ , %I ]
						",
						array($arr['id'] , $arr['id_user'] , $arr['pay_fee'] , $arr['pay_title'] , $arr['pay_text'] , $arr['bank_info'] , $arr['pay_status'] , $arr['pay_type'] , $arr['pay_date'], $order['by'], $order['sort'] ,$limit['start'],$limit['end']));
		if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}
    
    public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT COUNT(*) as Num FROM `gcms_khodro_pay` WHERE TRUE
					    [ AND `id` = %I ] 
                         [ AND `id_user` = %I ] 
                         [ AND `pay_fee` = %N ]
                         [ AND `pay_title` = %N ]
                         [ AND `pay_text` = %N ]
                         [ AND `bank_info` = %N ]
                         [ AND `pay_status` = %N ]
                         [ AND `pay_type` = %N ]
                         [ AND `pay_date` = %N ]
                        
						",
						array($arr['id'] , $arr['id_user'] , $arr['pay_fee'] , $arr['pay_title'] , $arr['pay_text'] , $arr['bank_info'] , $arr['pay_status'] , $arr['pay_type'] , $arr['pay_date']));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}

	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query("DELETE FROM `gcms_khodro_pay`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}

}   
    