<?php

/**
 * Talentofake.php
 *
 * This file is part of GCMS > MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: gcms_talentofake
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */

class Talentofake
{

	public function __construct()
	{

	}

	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"INSERT INTO `gcms_talentofake` (
				         `id`  , 
                         `fullname`  , 
                         `gender`  , 
                         `birthday`  , 
                         `height`  , 
                         `weight`  , 
                         `mainfoot`  , 
                         `nationality`  , 
                         `ethnicity`  , 
                         `currentteam`  , 
                         `posisions` 
						) VALUES(
						 NULL  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n 
						)", array($arr['fullname'] , $arr['gender'] , $arr['birthday'] , $arr['height'] , $arr['weight'] , $arr['mainfoot'] , $arr['nationality'] , $arr['ethnicity'] , $arr['currentteam'] , $arr['posisions']));
		return $GLOBALS['GCMS_DB']->query($query);
	}
    
    public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"UPDATE `gcms_talentofake` SET
						 `id` =  %i 
                         [ , `fullname` = %N ] 
                         [ , `gender` = %N ] 
                         [ , `birthday` = %N ] 
                         [ , `height` = %N ] 
                         [ , `weight` = %N ] 
                         [ , `mainfoot` = %N ] 
                         [ , `nationality` = %N ] 
                         [ , `ethnicity` = %N ] 
                         [ , `currentteam` = %N ] 
                         [ , `posisions` = %N ] 
                        
						WHERE `id` =  %i",
						array($arr['id'] , $arr['fullname'] , $arr['gender'] , $arr['birthday'] , $arr['height'] , $arr['weight'] , $arr['mainfoot'] , $arr['nationality'] , $arr['ethnicity'] , $arr['currentteam'] , $arr['posisions'], $arr['id']));
		return $GLOBALS['GCMS_DB']->query($query);
	}

    public function get($arr, $list = false, $order = "" , $limit = "")
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT * FROM `gcms_talentofake` WHERE TRUE
						 [ AND `id` = %I ] 
                         [ AND `fullname` = %N ]
                         [ AND `gender` = %N ]
                         [ AND `birthday` = %N ]
                         [ AND `height` = %N ]
                         [ AND `weight` = %N ]
                         [ AND `mainfoot` = %N ]
                         [ AND `nationality` = %N ]
                         [ AND `ethnicity` = %N ]
                         [ AND `currentteam` = %N ]
                         [ AND `posisions` = %N ]
                        
						[ ORDER BY %S ] 
						[ ORDER BY `%S` ] [ %S ] 
                        [ LIMIT %I ][ , %I ]
						",
						array($arr['id'] , $arr['fullname'] , $arr['gender'] , 
								$arr['birthday'] , $arr['height'] , $arr['weight'] , 
								$arr['mainfoot'] , $arr['nationality'] , $arr['ethnicity'] , 
								$arr['currentteam'] , $arr['posisions'], 
								$order['rand'],$order['by'], $order['sort'] 
								,$limit['start'],$limit['end']));
		if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}
    
    public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT COUNT(*) as Num FROM `gcms_talentofake` WHERE TRUE
					    [ AND `id` = %I ] 
                         [ AND `fullname` = %N ]
                         [ AND `gender` = %N ]
                         [ AND `birthday` = %N ]
                         [ AND `height` = %N ]
                         [ AND `weight` = %N ]
                         [ AND `mainfoot` = %N ]
                         [ AND `nationality` = %N ]
                         [ AND `ethnicity` = %N ]
                         [ AND `currentteam` = %N ]
                         [ AND `posisions` = %N ]
                        
						",
						array($arr['id'] , $arr['fullname'] , $arr['gender'] , $arr['birthday'] , $arr['height'] , $arr['weight'] , $arr['mainfoot'] , $arr['nationality'] , $arr['ethnicity'] , $arr['currentteam'] , $arr['posisions']));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}

	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query("DELETE FROM `gcms_talentofake`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}

}   
    