<?php
/**
 * Shiraz_user.php
 *
 * This file is part of GCMS > MODULE MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB:
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */


class Shiraz_user
{

	public function __construct()
	{

	}

	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
		->query(
				"INSERT INTO `gcms_shiraz_user` (
				`id`  ,
				`username`  ,
				`email`  ,
				`temp_code`  ,
				`password`  ,
				`password_salt`  ,
				`gender`  ,
				`level`  ,
				`status`  ,
				`cell`  ,
				`name`  ,
				`birthdate`  ,
				`address`  ,
				`avatar`  ,
				`plus_count`  ,
				`created_date`
		) VALUES(
				NULL  ,
				%n  ,
				%n  ,
				%n  ,
				%n  ,
				%n  ,
				%n  ,
				%n  ,
				%n  ,
				%n  ,
				%n  ,
				%n  ,
				%n  ,
				%n  ,
				%n  ,
				%n
		)", array($arr['username'] , $arr['email'] , $arr['temp_code'] , $arr['password'] , $arr['password_salt'] , $arr['gender'] , $arr['level'] , $arr['status'] , $arr['cell'] , $arr['name'] , $arr['birthdate'] , $arr['address'] , $arr['avatar'] , $arr['plus_count'] , $arr['created_date']));
		return $GLOBALS['GCMS_DB']->query($query);
	}

	public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
		->query(
				"UPDATE `gcms_shiraz_user` SET
				`id` =  %i
				[ , `username` = %N ]
				[ , `email` = %N ]
				[ , `temp_code` = %N ]
				[ , `password` = %N ]
				[ , `password_salt` = %N ]
				[ , `gender` = %N ]
				[ , `level` = %N ]
				[ , `status` = %N ]
				[ , `cell` = %N ]
				[ , `name` = %N ]
				[ , `birthdate` = %N ]
				[ , `address` = %N ]
				[ , `avatar` = %N ]
				[ , `plus_count` = %N ]
				[ , `created_date` = %N ]

				WHERE `id` =  %i",
				array($arr['id'] , $arr['username'] , $arr['email'] , $arr['temp_code'] , $arr['password'] , $arr['password_salt'] , $arr['gender'] , $arr['level'] , $arr['status'] , $arr['cell'] , $arr['name'] , $arr['birthdate'] , $arr['address'] , $arr['avatar'] , $arr['plus_count'] , $arr['created_date'], $arr['id']));
		return $GLOBALS['GCMS_DB']->query($query);
	}

	public function get($arr, $list = false, $order = "" , $limit = "")
	{
		$query=$GLOBALS['GCMS_SAFESQL']
		->query(
				"SELECT * FROM `gcms_shiraz_user` WHERE TRUE
				[ AND `id` = %I ]
				[ AND `username` = %N ]
				[ AND `email` = %N ]
				[ AND `temp_code` = %N ]
				[ AND `password` = %N ]
				[ AND `password_salt` = %N ]
				[ AND `gender` = %N ]
				[ AND `level` = %N ]
				[ AND `status` = %N ]
				[ AND `cell` = %N ]
				[ AND `name` = %N ]
				[ AND `birthdate` = %N ]
				[ AND `address` = %N ]
				[ AND `avatar` = %N ]
				[ AND `plus_count` = %N ]
				[ AND `created_date` = %N ]
				[ AND (`name` LIKE %N OR `email` LIKE %N )]

				[ ORDER BY `%S` ] [ %S ]
				[ LIMIT %I ][ , %I ]
				",
				array($arr['id'] , $arr['username'] , $arr['email'] , $arr['temp_code'] , $arr['password'] , $arr['password_salt'] , $arr['gender'] , $arr['level'] , $arr['status'] , $arr['cell'] , $arr['name'] , $arr['birthdate'] , $arr['address'] , $arr['avatar'] , $arr['plus_count'] , $arr['created_date'], $arr['search'], $arr['search'], $order['by'], $order['sort'] ,$limit['start'],$limit['end']));
		if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}

	public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
		->query(
				"SELECT COUNT(*) as Num FROM `gcms_shiraz_user` WHERE TRUE
				[ AND `id` = %I ]
				[ AND `username` = %N ]
				[ AND `email` = %N ]
				[ AND `temp_code` = %N ]
				[ AND `password` = %N ]
				[ AND `password_salt` = %N ]
				[ AND `gender` = %N ]
				[ AND `level` = %N ]
				[ AND `status` = %N ]
				[ AND `cell` = %N ]
				[ AND `name` = %N ]
				[ AND `birthdate` = %N ]
				[ AND `address` = %N ]
				[ AND `avatar` = %N ]
				[ AND `plus_count` = %N ]
				[ AND `created_date` = %N ]

				",
				array($arr['id'] , $arr['username'] , $arr['email'] , $arr['temp_code'] , $arr['password'] , $arr['password_salt'] , $arr['gender'] , $arr['level'] , $arr['status'] , $arr['cell'] , $arr['name'] , $arr['birthdate'] , $arr['address'] , $arr['avatar'] , $arr['plus_count'] , $arr['created_date']));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}

	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
		->query("DELETE FROM `gcms_shiraz_user`
				WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}

}
