<?php

/**
 * SarfejoDfstufffee.php
 *
 * This file is part of GCMS > MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: gcms_sarfejo_dfstufffee
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */

class SarfejoDfstufffee
{

	public function __construct()
	{

	}

	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"INSERT INTO `gcms_sarfejo_dfstufffee` (
				         `id`  , 
                         `id_stuff`  , 
                         `fee`  , 
                         `date` 
						) VALUES(
						 NULL  , 
                         %i  , 
                         %n  , 
                         %n 
						)", array($arr['id_stuff'] , $arr['fee'] , $arr['date']));
		return $GLOBALS['GCMS_DB']->query($query);
	}
    
    public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"UPDATE `gcms_sarfejo_dfstufffee` SET
						 `id` =  %i 
                         [ , `id_stuff` = %I ] 
                         [ , `fee` = %N ] 
                         [ , `date` = %N ] 
                        
						WHERE `id` =  %i",
						array($arr['id'] , $arr['id_stuff'] , $arr['fee'] , $arr['date'], $arr['id']));
		return $GLOBALS['GCMS_DB']->query($query);
	}

    public function get($arr, $list = false, $order = "" , $limit = "" ,$join_param = "")
	{
        $join_query_helper=array();
        if($join_param=="param")
        {
            $join_query_helper['select']=" , `gcms_sarfejo_dfstuff`.name as name ";
            $join_query_helper['join']="INNER JOIN `gcms_sarfejo_dfstuff` ON `gcms_sarfejo_dfstufffee`.`id_stuff` = `gcms_sarfejo_dfstuff`.`id`";
        }
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT `gcms_sarfejo_dfstufffee`.*  [ %S ] FROM `gcms_sarfejo_dfstufffee` [ %S ]  WHERE TRUE
						 [ AND `gcms_sarfejo_dfstufffee`.`id` = %I ]
                         [ AND `gcms_sarfejo_dfstufffee`.`id_stuff` = %I ]
                         [ AND `gcms_sarfejo_dfstufffee`.`fee` = %N ]
                         [ AND `gcms_sarfejo_dfstufffee`.`date` = %N ]
                        
						[ ORDER BY `%S` ] [ %S ] 
                        [ LIMIT %I ][ , %I ]
						",
						array(
                            $join_query_helper['select'],
                            $join_query_helper['join'],
                            $arr['id'] , $arr['id_stuff'] , $arr['fee'] , $arr['date'], $order['by'], $order['sort'] ,$limit['start'],$limit['end']));
        if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}
    
    public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT COUNT(*) as Num FROM `gcms_sarfejo_dfstufffee` WHERE TRUE
					    [ AND `id` = %I ] 
                         [ AND `id_stuff` = %I ] 
                         [ AND `fee` = %N ]
                         [ AND `date` = %N ]
                        
						",
						array($arr['id'] , $arr['id_stuff'] , $arr['fee'] , $arr['date']));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}

	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query("DELETE FROM `gcms_sarfejo_dfstufffee`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}

}   
    