<?php

/**
 * Account.php
 *
 * This file is part of GCMS > MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: gcms_account
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */

class Account
{

	public function __construct()
	{

	}

	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"INSERT INTO `gcms_account` (
				         `id`  , 
                         `user_id`  , 
                         `title`  , 
                         `fee`  , 
                         `date`  , 
                         `register_date`  , 
                         `txt`  , 
                         `id_author` 
						) VALUES(
						 NULL  , 
                         %i  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %n  , 
                         %i 
						)", array($arr['user_id'] , $arr['title'] , $arr['fee'] , $arr['date'] , $arr['register_date'] , $arr['txt'] , $arr['id_author']));
		return $GLOBALS['GCMS_DB']->query($query);
	}
    
    public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"UPDATE `gcms_account` SET
						 `id` =  %i 
                         [ , `user_id` = %I ] 
                         [ , `title` = %N ] 
                         [ , `fee` = %N ] 
                         [ , `date` = %N ] 
                         [ , `register_date` = %N ] 
                         [ , `txt` = %N ] 
                         [ , `id_author` = %I ] 
                        
						WHERE `id` =  %i",
						array($arr['id'] , $arr['user_id'] , $arr['title'] , $arr['fee'] , $arr['date'] , $arr['register_date'] , $arr['txt'] , $arr['id_author'],$arr['id'] ));
		return $GLOBALS['GCMS_DB']->query($query);
	}

    public function get($arr, $list = false, $group = "" , $order = "" , $limit = "")
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT * FROM `gcms_account` WHERE TRUE
						 [ AND `id` = %I ] 
                         [ AND `user_id` = %I ] 
                         [ AND `title` = %N ]
                         [ AND `fee` = %N ]
                         [ AND `date` = %N ]
                         [ AND `date` BETWEEN %N and %N]
                         [ AND `register_date` = %N ]
                         [ AND `txt` = %N ]
                         [ AND `id_author` = %I ] 
                        [ GROUP BY `%S` ] [, %S ] 
						[ ORDER BY `%S` ] [ %S ] 
                        [ LIMIT %I ][ , %I ]
						",
						array($arr['id'] , $arr['user_id'] , $arr['title'] , $arr['fee'] , $arr['date'] ,$arr['datefrom'] ,$arr['dateto'] , $arr['register_date'] , $arr['txt'] , $arr['id_author'], $group['by'], $group['andby'], $order['by'], $order['sort'] ,$limit['start'],$limit['end']));

		if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}
    
    public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT COUNT(*) as Num FROM `gcms_account` WHERE TRUE
					    [ AND `id` = %I ] 
                         [ AND `user_id` = %I ] 
                         [ AND `title` = %N ]
                         [ AND `fee` = %N ]
                         [ AND `date` = %N ]
                         [ AND `register_date` = %N ]
                         [ AND `txt` = %N ]
                         [ AND `id_author` = %I ] 
                       
						",
						array($arr['id'] , $arr['user_id'] , $arr['title'] , $arr['fee'] , $arr['date'] , $arr['register_date'] , $arr['txt'] , $arr['id_author']));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}

	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query("DELETE FROM `gcms_account`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}
	
	public function get_sum_service_fee($user_id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
		->query(" SELECT SUM(fee) as Sum  FROM `gcms_account` as a WHERE
				[  `a`.`user_id` = %I ]
				", array($user_id));
		//echo $query."<br/>";
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Sum;
	}

}   
    