<?php

/**
 * Tickettime.php
 *
 * This file is part of GCMS > MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: gcms_tickettime
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */

class Tickettime
{

	public function __construct()
	{

	}

	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"INSERT INTO `gcms_tickettime` (
				         `id`  , 
                         `id_ticket`  , 
                         `hour`  , 
                         `available` 
						) VALUES(
						 NULL  , 
                         %i  , 
                         %n  , 
                         %n 
						)", array($arr['id_ticket'] , $arr['hour'] , $arr['available']));
		return $GLOBALS['GCMS_DB']->query($query);
	}
    
    public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"UPDATE `gcms_tickettime` SET
						 `id` =  %i 
                         [ , `id_ticket` = %I ] 
                         [ , `hour` = %N ] 
                         [ , `available` = %N ] 
                        
						WHERE `id` =  %i",
						array($arr['id'] , $arr['id_ticket'] , $arr['hour'] , $arr['available'], $arr['id']));
		return $GLOBALS['GCMS_DB']->query($query);
	}

    public function get($arr, $list = false, $order = "" , $limit = "")
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT * FROM `gcms_tickettime` WHERE TRUE
						 [ AND `id` = %I ] 
                         [ AND `id_ticket` = %I ] 
                         [ AND `hour` = %N ]
                         [ AND `available` = %N ]
                        
						[ ORDER BY `%S` ] [ %S ] 
                        [ LIMIT %I ][ , %I ]
						",
						array($arr['id'] , $arr['id_ticket'] , $arr['hour'] , $arr['available'], $order['by'], $order['sort'] ,$limit['start'],$limit['end']));
		if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
		else
			return $GLOBALS['GCMS_DB']->get_row($query);
	}
    
    public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query(
						"SELECT COUNT(*) as Num FROM `gcms_tickettime` WHERE TRUE
					    [ AND `id` = %I ] 
                         [ AND `id_ticket` = %I ] 
                         [ AND `hour` = %N ]
                         [ AND `available` = %N ]
                        
						",
						array($arr['id'] , $arr['id_ticket'] , $arr['hour'] , $arr['available']));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}

	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
				->query("DELETE FROM `gcms_tickettime`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}

}   
    