<?php

/**
 * Ticket.php
 *
 * This file is part of GCMS > MODEL
 * The file is part of the layer for interacting with database.
 * Linked table in DB: gcms_ticket
 *
 * @author AutoGenerated <25Mordad@gmail.com>
 * @version 2.0
 *
 */
require_once(__COREROOT__."/module/ticket/model/Type.php");
require_once(__COREROOT__."/module/ticket/model/Ticketprice.php");

class Ticket
{
	
	public function __construct()
	{
		
	}
	
	public function insert($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
		->query(
				"INSERT INTO `gcms_ticket` (
				         `id`  ,
                         `country`  ,
                         `state`  ,
                         `city`  ,
                         `googlemap`  ,
                         `meetingpoint`  ,
                         `title`  ,
                         `description`  ,
                         `status`  ,
                         `bookstatus`  ,
                         `ticketorder`  ,
                         `tickettype`  ,
                         `author_id`  ,
                         `created_date`  ,
                         `modified_date`
						) VALUES(
						 NULL  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %n  ,
                         %i  ,
                         %n  ,
                         %n
						)", array($arr['country'] , $arr['state'] , $arr['city'] , $arr['googlemap'] , $arr['meetingpoint'] , $arr['title'] , $arr['description'] , $arr['status'] , $arr['bookstatus'] , $arr['ticketorder'] , $arr['tickettype'] , $arr['author_id'] , $arr['created_date'] , $arr['modified_date']));
		$GLOBALS['GCMS_DB']->query($query);
		return  mysql_insert_id();
	}
	
	public function update($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
		->query(
				"UPDATE `gcms_ticket` SET
						 `id` =  %i
                         [ , `country` = %N ]
                         [ , `state` = %N ]
                         [ , `city` = %N ]
                         [ , `googlemap` = %N ]
                         [ , `meetingpoint` = %N ]
                         [ , `title` = %N ]
                         [ , `description` = %N ]
                         [ , `status` = %N ]
                         [ , `bookstatus` = %N ]
                         [ , `ticketorder` = %N ]
                         [ , `tickettype` = %N ]
                         [ , `author_id` = %I ]
                         [ , `created_date` = %N ]
                         [ , `modified_date` = %N ]
				
						WHERE `id` =  %i",
				array($arr['id'] , $arr['country'] , $arr['state'] , $arr['city'] , $arr['googlemap'] , $arr['meetingpoint'] , $arr['title'] , $arr['description'] , $arr['status'] , $arr['bookstatus'] , $arr['ticketorder'] , $arr['tickettype'] , $arr['author_id'] , $arr['created_date'] , $arr['modified_date'], $arr['id']));
		return $GLOBALS['GCMS_DB']->query($query);
	}
	
	public function get($arr, $list = false, $order = "" , $limit = "")
	{
		$query=$GLOBALS['GCMS_SAFESQL']
		->query(
				"SELECT * FROM `gcms_ticket` WHERE TRUE
						 [ AND `id` = %I ]
                         [ AND `country` = %N ]
                         [ AND `state` = %N ]
                         [ AND `city` = %N ]
                         [ AND `googlemap` = %N ]
                         [ AND `meetingpoint` = %N ]
                         [ AND `title` = %N ]
                         [ AND `description` = %N ]
                         [ AND `status` = %N ]
                         [ AND `bookstatus` = %N ]
                         [ AND `ticketorder` = %N ]
                         [ AND `tickettype` = %N ]
                         [ AND `author_id` = %I ]
                         [ AND `created_date` = %N ]
                         [ AND `modified_date` = %N ]
				
						[ ORDER BY `%S` ] [ %S ]
                        [ LIMIT %I ][ , %I ]
						",
				array($arr['id'] , $arr['country'] , $arr['state'] , $arr['city'] , $arr['googlemap'] , $arr['meetingpoint'] , $arr['title'] , $arr['description'] , $arr['status'] , $arr['bookstatus'] , $arr['ticketorder'] , $arr['tickettype'] , $arr['author_id'] , $arr['created_date'] , $arr['modified_date'], $order['by'], $order['sort'] ,$limit['start'],$limit['end']));
		if($list)
			return $GLOBALS['GCMS_DB']->get_results($query);
			else
				return $GLOBALS['GCMS_DB']->get_row($query);
	}
	
	public function get_count($arr)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
		->query(
				"SELECT COUNT(*) as Num FROM `gcms_ticket` WHERE TRUE
					    [ AND `id` = %I ]
                         [ AND `country` = %N ]
                         [ AND `state` = %N ]
                         [ AND `city` = %N ]
                         [ AND `googlemap` = %N ]
                         [ AND `meetingpoint` = %N ]
                         [ AND `title` = %N ]
                         [ AND `description` = %N ]
                         [ AND `status` = %N ]
                         [ AND `bookstatus` = %N ]
                         [ AND `ticketorder` = %N ]
                         [ AND `tickettype` = %N ]
                         [ AND `author_id` = %I ]
                         [ AND `created_date` = %N ]
                         [ AND `modified_date` = %N ]
				
						",
				array($arr['id'] , $arr['country'] , $arr['state'] , $arr['city'] , $arr['googlemap'] , $arr['meetingpoint'] , $arr['title'] , $arr['description'] , $arr['status'] , $arr['bookstatus'] , $arr['ticketorder'] , $arr['tickettype'] , $arr['author_id'] , $arr['created_date'] , $arr['modified_date']));
		$result=$GLOBALS['GCMS_DB']->get_results($query);
		return $result[0]->Num;
	}
	
	public function del($id)
	{
		$query=$GLOBALS['GCMS_SAFESQL']
		->query("DELETE FROM `gcms_ticket`
						WHERE `id` =  %i", array($id));
		return $GLOBALS['GCMS_DB']->query($query);
	}
	
}
